### ISSUE TITLE
Provide a new validation method that is checking the full schematron xml structure.

### ISSUE THREAD

**Issue by monicabaciu** [phax/ph-schematron#1]
This method should not stop at the first validation error. instead, it should scan the whole schematron xml structure to identyfy all the invalid elements and report the errors.

**Comment by R00dRallec** [comment]
Is this already implemented ?

**Comment by phax** [comment]
Kind of. Not all errors can really be handled sequentially, but SchematronResourcePure offers a method "validateCompletely" which uses the internal IPSErrorHandler for error collection. In the trunk the API was extended to accept an alternative error handler.

**Comment by phax** [comment]
@monicabaciu Does this "validateCompletely" fit your needs?

**Comment by phax** [comment]
I received an email, and this is done.
