### ISSUE TITLE
ph-schematron-5.5.0.jar with Java 1.7

### ISSUE THREAD

**Issue by manuelhcosta** [phax/ph-schematron#100]
Hello Philip,

With Java 1.8 and and ph-schematron-5.5.0.jar I can validate the UBL
Invoice XML, but the framework where I have to validate this XML use Java
1.7.
When I try to validate with Java 1.7, I receive the
following error: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad
major version; class=com/helger/schematron/ISchematronResource, offset=6.

Is it possible to use  ph-schematron-5.5.0.jar in Java 1.7 ?

Thanks in advance.

Regards,

Manuel Costa

**Comment by phax** [comment]
Hi Manuel,
no unfortunately not - all base libraries etc. require Java 1.8 as the basis.
Using Java 1.7 is no option at all - sorry.
BR, Philip

**Comment by manuelhcosta** [comment]
Hi Philip,

Thanks anyway.

Regards,

Manuel
