### ISSUE TITLE
Rich attributes fpi, see, and possibly others are not returned in svrl report

### ISSUE THREAD

**Issue by Michiel-s** [phax/ph-schematron#101]
Hi @phax,

First of all, thanks for this great schematron validation implementation.

I'm using version 5.6.0.

When I have e.g. the following rule set
```xml
<sch:pattern id="1000101">
   <sch:title>Rule title</sch:title>
   <sch:rule id="1000101" fpi="BR-123" context="some xpath here">
      <sch:assert fpi="BR123-1" flag="error" see="#/rules/1000101" test="some test here">Some error message here</sch:assert>
    </sch:rule>
</sch:pattern>
```

The attribute `fpi` (both for rule and assert) and `see` are not returned in the svrl output:
```xml
<ns2:schematron-output title="" schemaVersion="">
    <ns2:active-pattern id="1000101" name="Rule title" document=""/>
    <ns2:fired-rule id="1000101" context="some xpath here"/>
    <ns2:fired-rule id="1000101" context="some xpath here"/>
    <ns2:failed-assert location="xpath location" test="the test again" flag="error">
        <ns2:text>Some error message here</ns2:text>
    </ns2:failed-assert>
</ns2:schematron-output>
```
As you can see, the `id` and `flag` attributes are there, but not the `fpi` and `see`. They are part of the schematron and svrl specs and I also see some references to those attributes in your code.

Is this a bug, feature or am I missing some config that I need to use.

Michiel

**Comment by phax** [comment]
Hi Michiel,
thanks for your question.
May I ask what version of the Schematron engine you are using? Pure, SCH or XSLT? Because that has an impact on the outcome :)
Thanks, Philip

**Comment by Michiel-s** [comment]
I’m not using the Pure engine, but not sure what you mean by SCH vs XSLT. I’m creating a new schematron resource with SchematronResourceSCH class. So I think the SCH engine then. But as far as I understood and see in the logs, this translates to xslt for the actual validation process.

**Comment by phax** [comment]
Yes exactly - the SCH is converted to an XSLT and than applied onto the main XML to created SVRL.
In that case I cannot help you, as this is basically the "default XSLT" from schematron.com (see https://github.com/Schematron/schematron )
I scanned the issues but couldn't find something.... 
Please open an issue there - okay?

**Comment by phax** [comment]
Closing this, as there is unfortunately not much I can do here :(

**Comment by flowrider3000** [comment]
@Michiel-s check my pr #111 for an example how to add `allow-foreign` elements.

**Comment by Michiel-s** [comment]
Thx. I'll look into it probably Monday. Thanks for mentioning me.

**Comment by phax** [comment]
My SVRL output is currently this:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schematron-output xmlns="http://purl.oclc.org/dsdl/svrl" schemaVersion="" title="">
<!--   
		   
		   
		 -->
  <active-pattern document="C:\dev\git\ph-schematron\ph-schematron\src\test\resources\issues\github101\test.xml" id="p1000101" name="Rule title" />
  <fired-rule context="/doc/h1" fpi="BR-123" id="r1000101" />
  <failed-assert flag="error" fpi="BR123-1" location="/doc[1]/h1[1]" see="#/rules/1000101" test="@a='b'">
    <text>Some error message here</text>
  </failed-assert>
  <fired-rule context="/doc/h1" fpi="BR-123" id="r1000101" />
  <fired-rule context="/doc/h1" fpi="BR-123" id="r1000101" />
  <failed-assert flag="error" fpi="BR123-1" location="/doc[1]/h1[3]" see="#/rules/1000101" test="@a='b'">
    <text>Some error message here</text>
  </failed-assert>
</schematron-output>
```

it fails because attribute `fpi` is not allowed in `svrl:fired-rule`

**Comment by phax** [comment]
It should be working in the 6.0.0 version

**Comment by flowrider3000** [comment]
@phax many thanks. Do you have any eta when 6.0.0 will be available?

**Comment by phax** [comment]
No not really. I am splitting things into more modules and want to add schxslt as well - if this is done, v6 is free to be published

**Comment by phax** [comment]
Version 6.0.0 is on it's way to Maven Central. Please see https://github.com/phax/ph-schematron/wiki/Migrations for details
