### ISSUE TITLE
SchematronResourceSCH.fromFile method does not detect changes on filesystem

### ISSUE THREAD

**Issue by Michiel-s** [phax/ph-schematron#102]
Version: 5.6.0

In our use case, a schematron file was changed on the mounted filesystem, but the schematron caching mechanism did not pick up this change. Caching seems to be done based on filepath. Is this expected behavior?

We use the SchematronResourceSCH.fromFile() method

@phax what do you recommend? Is there another method/constructor available?

**Comment by phax** [comment]
Yes, this is purely file path based. If you need "smarter" caching you need to add this separately "around" ph-schematron - sorry. But you can avoid double caching via `setUseCache (false)`

**Comment by Michiel-s** [comment]
Thx for the quick response. We know what to do.
