### ISSUE TITLE
com.helger.schematron.svrl.jaxb.SchematronOutputType missing?

### ISSUE THREAD

**Issue by electrickery** [phax/ph-schematron#105]
Hi,

A build from a clean git clone results in failing tests, indicating the com.helger.schematron.svrl.jaxb.SchematronOutputType class is not found. The documentation mentions it is generated, 

Build > Rebuild Project (IntelliJ here) results in:
...\ph-schematron\src\main\java\com\helger\schematron\AbstractSchematronResource.java:39:39
java: package com.helger.schematron.svrl.jaxb does not exist.

**Comment by phax** [comment]
Yes, if you run `mvn install` or `mvn process-sources` on the commandline, it creates a folder `target/generated-sources/xjc` and that needs to be added to your build path.
As an Eclipse use I can't tell you too much how IntelliJ handles this 🤷

**Comment by electrickery** [comment]
Thank you for your response. 'mvn install' worked perfectly. 
From IntelliJ I had in File > Project Structure > Project Settings > Modules, mark the .../ph-schematron/ph-schematron/target/generated-sources/svrl directory as "Sources".
There is still an issue with failing unit-tests, but not with 'mvn install', so I consider it an other IntelliJ config issue.

**Comment by phax** [comment]
There is a difference in the "current directory" between Eclipse and IntelliJ - so if you adopt the current working directory, it might help.
