### ISSUE TITLE
what should i do to update  the s_aCache  

### ISSUE THREAD

**Issue by SnowMakerDemo** [phax/ph-schematron#109]
![image](https://user-images.githubusercontent.com/28621460/98088488-77f28700-1ebc-11eb-8ce6-6604313f1301.png)
s_aCache  has cached file.sch ,but content of this file is changed, i want to update the cacheMap ,what shoud i do  

**_ How about  || m_bForceCacheResult_**  
`SchematronProviderXSLTFromSCH aProvider = s_aCache.get (sCacheKey);
      if (aProvider == null  || m_bForceCacheResult)
      {
        // Create new object and put in cache
        aProvider = createSchematronXSLTProvider (aSchematronResource, aTransformerCustomizer);
        if (aProvider != null)
          s_aCache.put (sCacheKey, aProvider);
      }`

**Comment by phax** [comment]
Sorry for the delay. Finally a clearCache is here. Will be part of the 5.6.5 release.
