### ISSUE TITLE
Possible bug: Diagnostics don't work when using abstract rules

### ISSUE THREAD

**Issue by barrys52** [phax/ph-schematron#11]
I am using the validateXMLViaPureSchematron when performing validation.  Here's the snippet:

```java
File schFile = new File("simpleAbstract.sch");
File xmlFile = new File("simple.xml");
SchematronOutputType schematronOutputType = validateXMLViaPureSchematron(schFile, xmlFile);
System.out.println(schematronOutputType);
```

The simpleAbstract.sch:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://purl.oclc.org/dsdl/schematron">
  <title>Length check</title>
  <pattern name="AbstractRules" id="abstracts">
    <rule abstract="true" id="lengthCheck">
      <assert test="string-length(A) &lt;=10">
        A exceeds 10 characters
      </assert>
      <assert test="string-length(B) &lt;=5">
        B exceeds 5 characters
      </assert>
    </rule>
  </pattern>

  <pattern id="length-checks">
    <rule context="X">
      <extends rule="lengthCheck"/>
    </rule>
    <rule context="Y">
      <extends rule="lengthCheck"/>
    </rule>
  </pattern>

  <pattern id="structure">
    <rule context="simple">
      <assert test="Z" diagnostics="d1">
        Does not contain Z element
      </assert>
    </rule>
  </pattern>

  <diagnostics>
    <diagnostic id="d1">
      Diagnostic d1 <value-of select="title"/>
    </diagnostic>
  </diagnostics>
</schema>
```

The simple.xml:
```xml
<simple>
  <title>Example</title>
  <X>
    <A>This is string XA</A>
    <B>This is string XB</B>
  </X>
  <Y>
    <A>This is string YA</A>
    <B>This is string YB</B>
  </Y>
</simple>
```

When the "abstracts" and "length-checks" elements are commented out, this is the result of the fired rule:
```
[FiredRule@0x2aa3cd93: id=null; context=//simple; role=null; flag=null], [FailedAssert@0x7ea37dbf: diagnosticReference=[[DiagnosticReference@0x4b44655e: text=
      Diagnostic d1 Example
    ; diagnostic=d1]]; text=
        Does not contain Z element
      ; id=null; location=/simple; test=Z; role=null; flag=null]]; title=Length check; phase=null; schemaVersion=null]
```
However, when "abstracts" is uncommented (length-checks can remain commented), the result of the fired rule is missing the diagnositc:
```
[FiredRule@0x290d210d: id=null; context=//simple; role=null; flag=null], [FailedAssert@0x1d76aeea: diagnosticReference=[]; text=
        Does not contain Z element
      ; id=null; location=/simple; test=Z; role=null; flag=null]]; title=Length check; phase=null; schemaVersion=null]
```

**Comment by phax** [comment]
Before a Schematron is executed it is checked whether it is minimal syntax or not (see chapter 6.2 of the ISO spec). If it is not "preprocessed" (in my terms), preprocessing happens using the class `PSPreprocessor`.
But anyway I noted a difference between the XSLT based version and the Pure version. In the XSLT based version reports were kept, diagnostics were kept and the title was kept. In the Pure implementation only the title was kept. I unified this in the master branch so that diagnostics are also kept in Pure implementation.

Can you test this against the trunk or do you need a release?

**Comment by barrys52** [comment]
I've tested it and the diagnostics are now working when abstract rules are present.   Thanks for the quick response!

**Comment by phax** [comment]
If it is working for you: I plan to do it tonight.

**Comment by barrys52** [comment]
I have one other question.  I cannot get an <include href="..."/> to work with the Pure version (haven't tried with the XSLT version).  Is this also an issue with the Pure version?

**Comment by phax** [comment]
What are the exact problems you have? Please elaborate a bit :)

**Comment by barrys52** [comment]
Using the above example, let's say I move the pattern with id="abstracts" to it's own file, say abstracts.sch.  Then replace that pattern in simpleAbstract.sch with:

```
<include href="abstracts.sch"/>
```
Then, I get this when the validateXMLViaPureSchematron method is called:

```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid Schematron!
	at gov.ic.dodiis.jitfct.schematron.test.AppSch.validateXMLViaPureSchematron(AppSch.java:21)
	at gov.ic.dodiis.jitfct.schematron.test.AppSch.main(AppSch.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```
I have tried several variations of the abstract.sch: enclosing the element inside of a <schema> element and using "abstracts.sch#abstracts" in the href of the include (as your gc4 example uses).  All variations result in an Invalid Schematron exception. Is the problem with the way I'm specifying the include?

**Comment by phax** [comment]
Does your include file start with a schema element? If so please remove it. The included element must be the root element of the included document. Maybe there was previous warning on the console?
Did you specify a custom logging handler??

**Comment by barrys52** [comment]
Here's what abstract.sch is:

```
<?xml version="1.0" encoding="UTF-8"?>
<pattern name="AbstractRules" id="abstracts">
    <rule abstract="true" id="lengthCheck">
      <assert test="string-length(A) &lt;=10">
        A exceeds 10 characters
      </assert>
      <assert test="string-length(B) &lt;=5">
        B exceeds 5 characters
      </assert>
    </rule>
</pattern>
```
And here's the start of the schematron file:

```
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://purl.oclc.org/dsdl/schematron">
  <title>Length check</title>

  <include href="abstract.sch"/>
```

**Comment by phax** [comment]
I see the problem. First of all I added a call to the error handler on this special case.
The error message is now: `Failed to resolve rule ID 'lengthCheck' in extends statement. Available rules are: []` - I'm investigating

**Comment by phax** [comment]
Btw. next time create a new issue please :)

**Comment by phax** [comment]
Ah... the include file lacks the XML namespace `xmlns="http://purl.oclc.org/dsdl/schematron`.
I will create a respective error message for this

**Comment by phax** [comment]
After a pull you should see nice error messages :)

**Comment by barrys52** [comment]
Thanks again!  I have it working now.

**Comment by phax** [comment]
Excellent. I will than release 3.0.1

**Comment by phax** [comment]
Will be on Maven central soon
