### ISSUE TITLE
Revert to Saxon version 9*?

### ISSUE THREAD

**Issue by flowrider3000** [phax/ph-schematron#112]
Hi @phax , 

thanks for this nice lib!

During investigation for #111 I found some comments in the official schematron files that they were only tested with Saxon9* (see https://github.com/phax/ph-schematron/blob/master/ph-schematron/src/main/resources/schematron/20100710-xslt2/iso_dsdl_include.xsl#L82 or https://github.com/phax/ph-schematron/blob/master/ph-schematron/src/main/resources/schematron/20100710-xslt2/iso_schematron_skeleton_for_saxon.xsl#L192 for examples). Maybe it would make sense to revert the Saxon version to 9*? What do you think?

Best

**Comment by phax** [comment]
Hi Flo,
thanks for your question.
Well, I am fully confident that Michael Kay is a huge fan of backwards compatibility and as such this should work. Being forced to use an old, out-of-date version of a library does not sound very compelling to me.
Did you experience some specific issues, or is this just a "stomach feeling" of yours?
Btw. I want to add schxslt anyway - I guess one of the 2 will do the trick if the other one fails.
hth, Philip

**Comment by phax** [comment]
And as the ISO Schematron repository https://github.com/Schematron/schematron went read-only we cannot assume they are moving forward with Saxon 10 support anyway...

**Comment by flowrider3000** [comment]
Hi Philip,
I experienced no issues with Saxon10 so far. It was just a gut feeling and I wanted to check if you are aware of those comments. You can close the ticket if you want.
Best

**Comment by zzllkk2003** [comment]
hi phax,  

The Saxon-HE version does not support the use of custom extension functions in xslt. If used after 11. So how should we use the function in xslt?

please see at https://www.saxonica.com/documentation9.5/extensions/functions/saxon-extension-functions.html
