### ISSUE TITLE
Sub-Dependency convergence error: ph-xsds-xml:2.4.1   -  ph-commons:9.5.0

### ISSUE THREAD

**Issue by jpwijbenga** [phax/ph-schematron#114]
![afbeelding](https://user-images.githubusercontent.com/6123882/103904356-754f2080-50fd-11eb-8274-79a61f524e1c.png)

Maven fails to build after I upgrade to 6.0.2. Is this a caching thing or is there a dependency error? Or does nobody use this maven plugin :P ?

**Comment by phax** [comment]
Hi, this is not a "real" problem.
ph-commons 9.5.4 is compatible to ph-commons 9.5.0.
Is it possibe for you to adopt the respective rules from the maven-enforcer plugin?

**Comment by jpwijbenga** [comment]
Yeah, will do that. Subdependency exclusions are the way to go to fix this here.
For reference:  https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html

**Comment by phax** [comment]
Great thanks :) Happy Schematroning
