### ISSUE TITLE
The  example code link is broken on the main page at http://phax.github.io/ph-schematron/

### ISSUE THREAD

**Issue by kal99** [phax/ph-schematron#12]
The  example code link is broken at http://phax.github.io/ph-schematron (https://github.com/phax/ph-schematron/blob/master/src/test/java/com/helger/schematron/docs/DocumentationExamples.java)

**Comment by phax** [comment]
Thx for finding. Will be fixed asap...

**Comment by kal99** [comment]
Thanks. I am new to schematron and trying to use ph-schematron as it fits nicely into our existing maven build process. It will be good to get some detailed examples on the standard use of the XSLT implementation.

**Comment by phax** [comment]
The correct link is https://github.com/phax/ph-schematron/blob/master/ph-schematron/src/test/java/com/helger/schematron/docs/DocumentationExamples.java
