### ISSUE TITLE
Avoid having whole SVRL DOM in memory

### ISSUE THREAD

**Issue by robertmarkbram** [phax/ph-schematron#125]
Hi Philip,

I have a follow up on https://github.com/phax/ph-schematron/issues/124 if I may.

```xml
final Document document = schematronResource.applySchematronValidation(new StreamSource(new File(xbrlPath)));
```

There is a chance that the XML might be thousands of lines long and after this line, the whole DOM is in memory right? Any way that avoids it all being in memory?

Rob
:)

**Comment by phax** [comment]
Hi Rob,
Thanks for asking, but I think this question doesn't hit the target ;-)
Schematron is using XSLT for the main transformations and checks, and all the XSLT transformations are done in memory. So if you want to validate large XML files (> 50 MB) you already require tons of memory. The SVRL will clearly not be problem here :)
hth, Philip

**Comment by robertmarkbram** [comment]
I see. Very good point. Thanks for pointing that out. :)
