### ISSUE TITLE
I am new to JAVA and ph-schematron. I am getting the no main manifest attribute, in ph-schematron-pure-6.0.2.jar while running the jar or class file missing error running the ph-schematron-pure-6.0.2.java. Can some one help me please.

### ISSUE THREAD

**Issue by rmurali84** [phax/ph-schematron#127]

**Comment by phax** [comment]
Please try the latest version 6.2.8 and check if it still happens: https://github.com/phax/ph-schematron/releases/tag/ph-schematron-parent-pom-6.2.8 and https://repo1.maven.org/maven2/com/helger/schematron/

**Comment by phax** [comment]
And you cannot run "ph-schematron" standalone. You need to include it in an application

**Comment by rmurali84** [comment]
Dear Phax,

Thanks. I will try and come back if any further help or support is required.

Thanks and Regards,
Murali
