### ISSUE TITLE
Silence [DEBUG] messages

### ISSUE THREAD

**Issue by ruthrapr** [phax/ph-schematron#128]
Hi @phax ,

is there a way to silence "[DEBUG]" messages ? My log is full of 
```
[schematron] [DEBUG] Applying Schematron XSLT on XML [start]
[schematron] [DEBUG] Applying Schematron XSLT on XML [end]
```
and others debug messages.

I'm currently using `ph-schematron-ant-task-6.2.8-jar-with-dependencies.jar` called in an ANT task.
```Ant Build System
<target name="schematron.taskdef-init">
    <taskdef name="schematron" classname="com.helger.schematron.ant.Schematron"
        classpath="lib/ph-schematron-ant-task-6.2.8-jar-with-dependencies.jar"/>
</target>

<schematron schematronFile="sch/schematron.sch"
        expectSuccess="true" failOnError="${stop-process-on-error}"
        failOnValidationError="${stop-on-validation-error}" failOnValidationWarn="${stop-on-validation-warning}"
        failOnValidationInfo="${stop-on-validation-info}">
        <fileset dir="${dita.temp.dir}" includes="**/*.dita"/>
        <xmlcatalog refid="dita.catalog"/>
</schematron>
```

Thanks for your help

**Comment by ruthrapr** [comment]
Thanks for taking your time @phax 

It was possibility 1, we ran DITA Open Toolkit with --verbose argument, which seems to emit level `DEBUG` (instead of ` INFO` ?) ([Logging build information](https://www.dita-ot.org/dev/topics/logging.html)).

Anyway, thx again

**Comment by phax** [comment]
Okay cool. Glad you found it. Thanks for the solution.
Happy to hear that the software is used and beneficial.
