### ISSUE TITLE
Resource not being found when trying to call the applySchematronValidation api

### ISSUE THREAD

**Issue by kal99** [phax/ph-schematron#13]
Hi,
I have tried lots of different things but strangely I can't get the basic api to work when trying to use applySchematronValidation on the xslt and the pure implememtation to retrieve the svrl document. I am using the com.helger.commons.io.resource.ClassPathResource for the resource. The calling code looks like this;

final Document doc = validateXMLViaPureSchematronDoc(new File("src/test/resources/schematron.sch"),
				"src/test/resources/schematron.xml");

Code is as follows;

public Document validateXMLViaPureSchematronDoc(@Nonnull final File aSchematronFile, @Nonnull final String aXMLFile)
			throws Exception {

		final ISchematronResource aResPure = SchematronResourcePure.fromFile(aSchematronFile);
		if (!aResPure.isValidSchematron()) {
			throw new IllegalArgumentException("Invalid Schematron!");
		}
		final ClassPathResource resource = new ClassPathResource(aXMLFile);
		return aResPure.applySchematronValidation(resource);
	}

Any help much appreciated.

Many Thanks

**Comment by kal99** [comment]
I think this is very specific problen with my classpaths as I have managed to get to work in eclipse so closing this issuel

**Comment by phax** [comment]
The classpath in Eclipse with the m2e plugin is sometimes not 100% spec compliant compared to commandline Maven. Maybe you want to try `FileSystemResource` instead of `ClassPathResource`?

**Comment by phax** [comment]
Another common problem is to have Saxon and Xalan together in the classpath.. Ensure to only use Saxon...

**Comment by kal99** [comment]
Thanks. i did come across the Xalan problem!

**Comment by kal99** [comment]
'FileSystemResource'  works just fine now in the original code so thanks once again.

**Comment by kal99** [comment]
Hi,

Still using your plugin although it has not been used in anger yet. I am hoping to  start using it more once I get the go ahead to implement the business rules.

One thing that I have encountered recently is that to make the ph-schematron work I have had to set the system property for the TransformerFactory and this causes undesirable side effects in other applications that need to use the Xalan implementation instead of the Saxon one. Is there a web application specific way to set this just for the ph-schematron based application?

I am currently using the following;

System.setProperty("javax.xml.transform.TransformerFactory", "net.sf.saxon.TransformerFactoryImpl");


Regards

Khalil Rehman
Software Developer | Emerald Group Publishing
Tel: +44 (0)1274 785291 | E-mail: krehman@emeraldinsight.com<mailto:krehman@emeraldinsight.com>
www.emeraldgrouppublishing.com<http://www.emeraldgrouppublishing.com> | www.emeraldinsight.com<http://www.emeraldinsight.com>

[Description: twitter-bird-white-on-blue-png]Follow us on Twitter<http://www.twitter.com/emeraldglobal>
[Description: facebook_logo]Like us on Facebook<http://www.facebook.com/emeraldgrouppublishing>

P Please consider the environment before printing this email

**Comment by phax** [comment]
Hi!
I'm in the middle of transitioning the project to JDK 8 what I do with all my projects.
I will there use a fixed `TransformerFactory` so that the Xalan problems goes away....
hth

**Comment by phax** [comment]
If you are going for the HEAD version (SNAPSHOT should be on Maven Central soon) and you have Saxon in your classpath please try without the system property (if you are using JDK8)

**Comment by kal99** [comment]
Many Thanks. We are still using Java 6, but will be transitioning to jdk8 sometime this year.

Regards

Khalil Rehman
Software Developer | Emerald Group Publishing
Tel: +44 (0)1274 785291 | E-mail: krehman@emeraldinsight.com<mailto:krehman@emeraldinsight.com>
www.emeraldgrouppublishing.com<http://www.emeraldgrouppublishing.com> | www.emeraldinsight.com<http://www.emeraldinsight.com>

[Description: twitter-bird-white-on-blue-png]Follow us on Twitter<http://www.twitter.com/emeraldglobal>
[Description: facebook_logo]Like us on Facebook<http://www.facebook.com/emeraldgrouppublishing>

P Please consider the environment before printing this email
