### ISSUE TITLE
How do I determine if a tag contains an attribute before I check it?

### ISSUE THREAD

**Issue by mshen6666** [phax/ph-schematron#131]
Hi Philip,
         I want to check if an xml tag contains an attribute before making a judgment on it.like I want to check the item tag，but it has two formats. one of them like `<item root="xxxxxxxxxxx" extension="$"/>`,another one like `<item><part value="name"/></item>`,i just want to check who has  attribute with extension . how should i write sch file.now my sch file like 
`<sch:pattern>
    <sch:rule context="*/item[@extension !='']">
            <sch:assert test="contains(@extension,'$')">extension not contain '$'</sch:assert>
    </sch:rule>
  </sch:pattern>`
thx

**Comment by phax** [comment]
Hi,
Without being the biggest XPath specialist on the planet, I suggest you try this one:
```xml
<sch:pattern>
  <sch:rule context="//item[@extension]">
    <sch:assert test="contains(@extension,'$')">extension not contain '$'</sch:assert>
  </sch:rule
</sch:pattern>
```

**Comment by mshen6666** [comment]
Thank you very much for your prompt reply, I will try it!
