### ISSUE TITLE
Attribute @subject not used for location in SVRL result  

### ISSUE THREAD

**Issue by ericlop** [phax/ph-schematron#133]
In case of presence, attribute @subject from schematron rule should be used in  the SVRL Result instead of context path in the attribute @location . Otherwise, the XML node(s) or attribute(s) which is(are) the cause of the error/warning cannot be retrieved precisely

To be also in compliance with mapping defined in schematron page : https://schematron.com/document/3464.html

Thx,

**Comment by phax** [comment]
Thanks for the proposal.
What "Engine" are you using?
* Java "pure"
* XSLT (ISO Schematron based)
* XSLT (SchXslt based)

And can you eventually provide a small demo SCH with the usage of this attribute?

**Comment by ericlop** [comment]
Hello Philip,
We're using java "pure".

Our need is to be able to specify one  or several node(s)/attributes from context path in a single "subject"/"location". For example, a range of values for which the maximum cannot be less than the minimum :
```xml
<rule context="/path/ValueRange">
        <assert id="XXX" subject="@min @max" test="not(@min) or not(@max) or number(@min) &lt;= number(@max)"
                role="ERROR">
               min-max error
        </assert>
    </rule>
```
If the 2nd ValueRange node in /path does not check this rule, we expect in SVRL result to specify both attributes which cause the assertion failure :
```xml
    <failed-assert id="XXX" location="/path/ValueRange[1]/@min /path/ValueRange[1]/@max" test="not(@min) or not(@max) or number(@min) &lt;= number(@max)" role="ERROR">
        <text>
           min-max error
        </text>
```
Thx,
Eric

**Comment by phax** [comment]
This is finally contained in v8.0.0
