### ISSUE TITLE
Pure schematron configurable delimiter for ID pool

### ISSUE THREAD

**Issue by mmcareit** [phax/ph-schematron#138]
Hello,

The pure schematron implementation appends a unique integer suffix to assertion ids, implemented as: [PSPreprocessor.java#247](https://github.com/phax/ph-schematron/blob/master/ph-schematron-pure/src/main/java/com/helger/schematron/pure/preprocess/PSPreprocessor.java#L247) and [PreprocessorIDPool.java](https://github.com/phax/ph-schematron/blob/master/ph-schematron-pure/src/main/java/com/helger/schematron/pure/preprocess/PreprocessorIDPool.java).

Could there be a configurable delimiter introduced so the appended suffix can be identified more easily? The purpose would be to remove the suffix manually as a post-processing step of the SVRL.

The issue is that the SVRL contains assertion ids which do not exist in the original schematron definition.

Do you have any other suggestions to circumvent this behaviour in order to preserve the original assertion ids?

Thanks in advance.

**Comment by phax** [comment]
Via `PreprocessorIDPool.setDefaultSeparator` you can now make the default separator customizable. It's a static method so you need to call it once on startup. It ill be part of the 6.3.5 release
