### ISSUE TITLE
Jakarta support

### ISSUE THREAD

**Issue by cemo** [phax/ph-schematron#139]
Hi Philip,

I noticed you had already prepared common and support libraries to switch Jakarta. Would you please update to latest common and ph-xsds-xml? Commons have already 11.0.0 version but ph-xsds-xml need a version release If I see correctly. 

Thanks

**Comment by phax** [comment]
Hi @cemo
That is absolutely the plan. I am currently waiting for the release of the Maven JAXB Plugin (see the PR https://github.com/evolvedbinary/jvnet-jaxb-maven-plugin/pull/26).
Once I have the possibility to get all the XSDs recompiled using Jakarta, I can continue with the Migration to Jakarta and Java 11.

**Comment by cemo** [comment]
Situation is really terrible now. Jakarta namespace changes made situation horrible. It is very difficult to find the way. What I need to validate xml files with Schematron but I almost lost and waiting a bunch of project to be released or updated.  

Can you please reevaluate to switch back to your project? Since the changes is already ready, It can be better to move forward with your project.

**Comment by phax** [comment]
Okay, I will create a release but will not announce it in large, hoping that EvolvedBinary will do it to continue the maintenance.

**Comment by cemo** [comment]
Thank you so much. Will you release other dependent projects too?

**Comment by phax** [comment]
Yes, that is the plan. Because for the created Java classes it will make no difference

**Comment by cemo** [comment]
If you let me know when the releases are ready, I can give a try. I was already in the process of building all dependencies on my local box to check what is necessary to build.

**Comment by phax** [comment]
`com.helger.maven:jaxb40-maven-plugin:0.16.0` is on its way to Maven Central

**Comment by cemo** [comment]
All 3 related projects are released and latest codes of ph-schematron can be built without any problem. Thank you so much. I have no more class not found exceptions.

**Comment by phax** [comment]
Yes, an official version 7.0.0 is build tonight

**Comment by phax** [comment]
Release 7.0.0 based on Java 11 and JAXB 4.0 is out: https://github.com/phax/ph-schematron/releases/tag/ph-schematron-parent-pom-7.0.0

**Comment by cemo** [comment]
It was a huge afford. Thank you so much.
