### ISSUE TITLE
Concurrent Usage 

### ISSUE THREAD

**Issue by cemo** [phax/ph-schematron#141]
Hi @phax,

What is the recommended way of usage in a concurrent environment? Should I create a new `ISchematronResource` for each document to be validated? 

I guess compiling is taking some time and you are already caching SCH schemas but I wanted to be sure that what is the recommended way.

**Comment by phax** [comment]
The recommended way is to compile the SCH to XSLT at build-time using e.g. the Maven plugin.
Then in the code you are directly using `SchematronXSLT` as the basis for processing.

That spares the tedious compilation proces and usually saves a lot of execution time.
Additionally you can rely on the concurrent usage rules for XSLT :)

**Comment by phax** [comment]
This is the correct way. Internally the precompiled XSLT "Templates" object is cached, so that it is reused automatically. So the instance itself is not thread-safe, the cache is thread-safe. 

With `aResXSLT.setUseCache (boolean)` you can trigger the XSLT usage

**Comment by cemo** [comment]
Thank you so much.

**Comment by phax** [comment]
Btw. are you aware of my [ph-ubl](https://github.com/phax/ph-ubl) project that also has built-in support for UBLTR?

**Comment by cemo** [comment]
I am very surprised now. You have even tests with our invoice samples. I will try to learn more about it how can I use it.

**Comment by cemo** [comment]
@phax After many years I entered XML land again so please forgive my ignorance. Let me explain my use case first. 
We will take restful requests to communicate with government to create invoices and other related objects. We will not take XML requests from someone and validate them. We will just receive requests in a restful way to create invoices. 

I see that UBL is used for 3 main purpose in the project. Write documents, read documents, validate documents. Read and Validate is not necessary my use case since I create them myself. What will be the benefit of using UBL?

By the way your projects are the greatest piece of thing in whole my way. Thank you again so much.

**Comment by phax** [comment]
Hi @cemo no worries. If you already have a solution to creating your UBL file, than my library is of no big use for you. I just thought it might be...
Maybe it would make sense to include the UBLTR Schematrons in my [phive-rules](https://github.com/phax/phive-rules) document validation library. Can you pls point me to the official website where I can download the official Schematrons??? Thx

**Comment by cemo** [comment]
I have sent an email regarding files. I can even contribute to projects if you want. I guess it is not so much difficult for you but If you need any help, please let me know.

**Comment by phax** [comment]
I assume the base link is https://ebelge.gib.gov.tr/efaturamevzuat.html and the main package can be taken from https://ebelge.gib.gov.tr/dosyalar/kilavuzlar/e-FaturaPaketi.zip ?

**Comment by cemo** [comment]
Yes exactly.

**Comment by cemo** [comment]
You had already use an old version of these files in UBL. I will be glad if you update them as well.

**Comment by idilalemdar** [comment]
Hi @phax, here again after some 2 years :) 

I also am trying to create UBLTR invoices. I have the following gradle dependencies:

```
implementation group: 'com.helger.ubl', name: 'ph-ubltr', version: '9.0.3'
implementation group: 'com.helger.ubl', name: 'ph-ubl21-codelists', version: '9.0.3'
```

At first, I wasn't aware of the existence of UBLTR either like @cemo and tried to create the invoice using UBL2.1 instead:

```
UBL21Marshaller.UBL21JAXBMarshaller<InvoiceType> ubl21Writer = UBL21Marshaller.invoice();
InvoiceType invoice = createInvoice(ublData);
String invoiceStr = ubl21Writer.getAsString(invoice);
```

where createInvoice is my helper method creating the UBL 2.1 invoice.

Problem is, I need to add UBLExtensions field to the invoice like this:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
         xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
         xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
         xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
         xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"
         xmlns:qdt="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2"
         xmlns:ubltr="urn:oasis:names:specification:ubl:schema:xsd:TurkishCustomizationExtensionComponents"
         xmlns:udt="urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2"
         xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2 UBL-Invoice-2.1.xsd">
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionContent>
                <ds:Signature Id="somesignatureid">
                     ...
                    </ds:Signature>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
```

 However my IDE does not seem to find some relevant UBLTR schemas for UBLExtensions like `QualifiedDatatypes-2`, `TurkishCustomizationExtensionComponents` or `UnqualifiedDataTypesSchemaModule:2`. Therefore adding UBLExtensions and its child fields like above makes the invoice unparseable by UBL2.1 . I then installed ubltr 9.0.3 instead but this did not solve the problem. These xds's are still somehow missing. 

Besides, `UBLTRMarshaller` does not directly include an invoice marshaller like `UBL21Marshaller.invoice()` does, but instead there is something called `UBLTRMarshaller.trPackage()`. That seems to be including invoice as an element but if truth be told, it's a little confusing how to put an invoice into `trPackage`. Is there a more straightforward way like there is in `UBL21Marshaller`  in `UBLTRMarshaller` as well?

Sorry to be commenting on a closed issue, but I thought the context was same so I am writing under this issue. Thank you very much for any help, and my most profound congratulations on developing and maintaining a project like this!

**Comment by phax** [comment]
The issue was also posted on ph-ubl, so the last comment is ignored here :)
