### ISSUE TITLE
Attribute 'document' is not allowed to appear in element 'svrl:active-pattern'

### ISSUE THREAD

**Issue by pigelvy** [phax/ph-schematron#149]
Using SchematronResourceSCH (r7.0.1), the SVRL mashalling fails. It seems that the `active-pattern` contains the attribute `document` instead of `documents`.

Here's a simple JUnit test showing the problem.

``` java
@Test
  void simple_test() throws Exception {
    String xml = "<xml id='1'/>";

    String sch = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                 "<schema xmlns=\"http://purl.oclc.org/dsdl/schematron\" queryBinding=\"xslt2\">\n" +
                 "  <pattern>\n" +
                 "    <rule context=\"xml\"><assert test=\"exists(@id)\">No id</assert></rule>\n" +
                 "  </pattern>\n" +
                 "</schema>\n";

    final SchematronResourceSCH schResource = SchematronResourceSCH.fromString(sch, UTF_8);
    final SchematronOutputType schematronOutputType = schResource.applySchematronValidationToSVRL(new StringStreamSource(xml));


    final SVRLMarshaller svrlMarshaller = new SVRLMarshaller();
    svrlMarshaller.getAsString(schematronOutputType); // This throws an exception
  }
```

**Comment by phax** [comment]
I cannot reproduce this Exception on my side.

Looking at my (self-built) XSD, I can see this comment:
```xml
      <!-- [ph] Schematron 2016 adds this in favor of "document" -->
      <xs:attribute name="documents" type="xs:string"/>
...
      <xs:attribute name="document" type="xs:string"/>
```

So this is kind of Schematron-specification dependent.

The RNC of the 2006 specification contains this snippet:
![grafik](https://github.com/phax/ph-schematron/assets/196219/03646c7c-57da-4847-80e1-0080e55f6ce9)

The RNC of the 2016 specification contains the "documents" attribute:
![grafik](https://github.com/phax/ph-schematron/assets/196219/84a71825-9978-457a-8602-f8de64d8e382)

And ISO Schematron emits the `document` attribute:
![grafik](https://github.com/phax/ph-schematron/assets/196219/da5890bb-64a6-4b7e-8940-2822a8b4eb72)

And finally SchXslt 1.9.5 does it according to Schematron 2016:
![grafik](https://github.com/phax/ph-schematron/assets/196219/3e6405a8-0b54-4f85-a898-43ba570c4edf)

It is all very messy....

**Comment by phax** [comment]
Bascially by chosing an implementation you can decide what attribute you will get. Hope this works.
Or shall we modify the ISO Schematron XSLT to produce `documents` instead?
