### ISSUE TITLE
How to clear cache to allow dynamic updates to pure schematron validation?

### ISSUE THREAD

**Issue by barrys52** [phax/ph-schematron#15]
I am using the following code to read the schematron file:

    String schematronResourceFile = schematronResource.getFile();
    ISchematronResource aResPure = SchematronResourcePure.fromFile(schematronResourceFile);

Then validating an XML file with this code:
    
    SchematronOutputType result = aResPure.applySchematronValidationToSVRL(new StreamSource(aXMLFileIS));

I need to be able to update the schematron dynamically without restarting the program.  The schematronResourceFile will always be the same value (/path/to/schematron-file.sch) but the file's contents may change since the last call to fromFile().  I noticed that no matter what happens to the schematron file contents, the file updates are not reflected after the call to fromFile().  Digging into the ph-schematron code, it appears that the SchematronResourcePure class computes a PSBoundSchemaCacheKey which I believe uses the schematron file name, so the key will always be same and return the same cached schematron file.  

Can you please suggest how I can clear this cache prior to calling fromFile()?  Or provide a workaround?

Thanks.

**Comment by phax** [comment]
The simplest thing to do is to call `PSBoundSchemaCache.getInstance().clear()`.
Alternatively if you read the Schematron from a String (`fromString`) or from a byte[] (`fromByteArray`) it wont be cached, because it is not associated with a persistent resource.

**Comment by barrys52** [comment]
Clearing the cache worked.  Thanks!
