### ISSUE TITLE
Lower Version of ph-schematron is not compatible with Higher version of ph-commons

### ISSUE THREAD

**Issue by Agastya007** [phax/ph-schematron#154]
Hi @phax ,
Issue 1:
We are Using  <artifactId>ph-schematron</artifactId> version 5.6.5 and we need<artifactId> ph-commons </artifactId>
version 10.2.1 but there is change in groupId in the both dependencies,
When we tried excluding ph-commons from ph-schematron and using external dependency of ph-commons of version 10.2.1 
 schematron functionality is not working due to change in the group-id 
 any proper solution for this
 We are using the dependencies in our Pom.xml like this,
 
<dependency>
    <groupId>com.helger</groupId>
    <artifactId>ph-schematron</artifactId>
    <version>5.6.5</version>
        <exclusions>
               <exclusion>
              <groupId>com.helger</groupId>
          <artifactId>ph-commons</artifactId>
              </exclusion>
        </exclusions>
  </dependency>
  
<dependency>
    <groupId>com.helger.commons</groupId>
    <artifactId>ph-commons</artifactId>
    <version>10.2.1</version>
</dependency>

  NOTE: 
 To resolve this, we upgraded ph-schematron-xslt  to version:6.5.3, but in our code validation of schematron file is failing with this version.

**Comment by phax** [comment]
ph-schematron 5.6.5 is really old and depends on an old version of ph-commons (9.x).
In version 10 of ph-commons the group ID changed from `com.helger` to `com.helger.commons` and some other breaking changes were performed - see e.g. https://github.com/phax/ph-commons/releases/tag/ph-commons-parent-pom-10.0.0

So it is unlikely that ph-schematron 5.x will run with ph-commons 10.x

So updating to ph-schematron[-parent-pom] 6.3.4 with ph-commons[-parent-pom] 10.2.5 (latest release fixing a CVE) should work
