### ISSUE TITLE
Cannot find a 0-argument function named Q{http://www.w3.org/2005/xpath-functions}current()

### ISSUE THREAD

**Issue by KonradEichstaedt** [phax/ph-schematron#156]
I tried to using an schematron isosch file for xml validation. I decided to take the pure implementation for this. 

`<dependency>
        <groupId>com.helger.schematron</groupId>
        <artifactId>ph-schematron-pure</artifactId>
        <version>6.3.4</version>
    </dependency>`

I using this following code 

'XPathFactory factory = XPathHelper.createXPathFactorySaxonFirst();

      factory.setFeature(FeatureKeys.ALLOW_EXTERNAL_FUNCTIONS, true);
      factory.setFeature(FeatureKeys.TRACE_EXTERNAL_FUNCTIONS, true);
      factory.setFeature(FeatureKeys.ALLOW_SYNTAX_EXTENSIONS, true);
      XPathConfig config = new XPathConfig(factory,null,null);

      final SchematronResourcePure aResSCH = SchematronResourcePure.fromInputStream(null,schemaFileResource);
      aResSCH.setXPathConfig(config);

      final ByteArrayInputStream teiInputStream = new ByteArrayInputStream(
          xml.getBytes(StandardCharsets.UTF_8));
      final StringBuilder message = new StringBuilder();

      try {
        SchematronOutputType outputType = aResSCH.applySchematronValidationToSVRL(TransformSourceFactory.create(teiInputStream));
        SVRLHelper.getAllFailedAssertions(outputType).forEach(assertion -> {
          message.append(assertion.getText());
        });
      }catch (Exception error) {
        log.error("Error during generate SVRL Report", error);
      }'

The execution failed always with this error: 

ooking for function Q{http://www.w3.org/2005/xpath-functions}name#1
Trying net.sf.saxon.functions.registry.XPath31FunctionSet
2023-07-12 09:28:20.594 ERROR 607562 --- [           main] c.h.s.p.e.LoggingPSErrorHandler          : [error] [PSAssertReport] Failed to compile XPath expression in <report>: 'ancestor::tei:l[not(.//tei:note//tei:l[. = current()])]' with the following variables: {} (javax.xml.xpath.XPathExpressionException: net.sf.saxon.trans.XPathException: Cannot find a 0-argument function named Q{http://www.w3.org/2005/xpath-functions}current())

javax.xml.xpath.XPathExpressionException: net.sf.saxon.trans.XPathException: Cannot find a 0-argument function named Q{http://www.w3.org/2005/xpath-functions}current()
	at net.sf.saxon.xpath.XPathEvaluator.compile(XPathEvaluator.java:212) ~[Saxon-HE-12.3.jar:na]
	at com.helger.schematron.pure.bound.xpath.PSXPathBoundSchema._compileXPath(PSXPathBoundSchema.java:109) ~[ph-schematron-pure-6.3.4.jar:6.3.4]

Can you please help to fix this issue, Many Thanks

**Comment by KonradEichstaedt** [comment]
Many Thanks for your help but if I using the XSLT Implementation your library doesn't accept the isosch file

2023-07-12 10:21:10.594 ERROR 613701 --- [           main] c.h.s.x.SchematronProviderXSLTPrebuild   : XSLT read/compilation error for [[ReadableResourceInputStream@0x6c5c6d88: ResourceID=input-stream]; InputStream=java.io.BufferedInputStream@3e6e7e06]
javax.xml.transform.TransformerConfigurationException: net.sf.saxon.s9api.SaxonApiException: The supplied file does not appear to be a stylesheet

**Comment by phax** [comment]
Sorry, my bad. Please use `SchematronResourceSCH` if your source file is a `.sch` file.
The `SchematronResourceXSLT` can be used, if you precompile your Schematron to XSLT with the Maven Plugin aforehand.

**Comment by KonradEichstaedt** [comment]
I refactored my code and technically it works but the isosch doesn't find any within given xml file. 

try (InputStream schemaFileResource = createStreamSource(ID_ISOSCH_TEI_HSP).getInputStream()) {

      final SchematronResourceSCH schematron = SchematronResourceSCH.fromInputStream(null,schemaFileResource);

      final StringBuilder message = new StringBuilder();
      final boolean validation = schematron.getSchematronValidity(TransformSourceFactory.create(xml)).isValid();

      SchematronOutputType outputType = schematron.applySchematronValidationToSVRL(TransformSourceFactory.create(xml));
      SVRLHelper.getAllFailedAssertions(outputType).forEach(assertion -> {
        message.append(assertion.getText());
      });

Do you have any idea what the root cause could be?

**Comment by phax** [comment]
Well, therefore I need the SCH and the XML. The root cause is most likely a bug in the Schematron :)

**Comment by KonradEichstaedt** [comment]
Enclosed the xml and isosch file, could you please check this, Many Thanks for your support

**Comment by phax** [comment]
I don't see the attachment here. Eventually you need to ZIP it to make it work.
Accepted extensions are: `.gif,.jpeg,.jpg,.mov,.mp4,.png,.svg,.webm,.csv,.docx,.fodg,.fodp,.fods,.fodt,.gz,.log,.md,.odf,.odg,.odp,.ods,.odt,.patch,.pdf,.pptx,.tgz,.txt,.xls,.xlsx,.zip`

**Comment by KonradEichstaedt** [comment]
[schematronhsp.zip](https://github.com/phax/ph-schematron/files/12026594/schematronhsp.zip)
 Sorry for this

**Comment by KonradEichstaedt** [comment]
Do you have any news for me regarding the isosch validation?

**Comment by phax** [comment]
Nope. Didn't have sufficient time to dig into the problem. Stay tuned :)

**Comment by phax** [comment]
Can you please let me know, what kind of error you'd expect?

**Comment by KonradEichstaedt** [comment]
I expect an error regarding an empty ref attribute for this element: 

`<persName role="Autor" ref="">SThomas Bricot</persName>`

**Comment by phax** [comment]
Well, the only rule regarding the `@ref` attribute I find is
```xml
   <pattern id="schematron-constraint-hsp_cataloguing-relation-reforkeyorname-37">
      <rule context="tei:relation">
         <assert test="@ref or @key or @name">One of the attributes  'name', 'ref' or 'key' must be supplied</assert>
      </rule>
   </pattern>
```
There is also no rule on `persName`

**Comment by KonradEichstaedt** [comment]
What is with the when rule? This attribute should throw an error or isn't it? 

`<date when="dsfsdfs" type="primary">2012</date>`

**Comment by phax** [comment]
The check for `date` element is only for a specific one:
```xml
      <rule context="tei:surrogates/tei:bibl/tei:date">
         <assert test="@when[matches(.,'^[1,2]\d{3}-[0,1]\d{1}-\d{2}$')]"> @when
                      requires a date in the standard form: yyyy-mm-dd. </assert>
      </rule>
```
Yours is in `teiHeader/fileDesc/publicationStmt/date`

Please make sure you understand XPath and how it is applied before diving too deep into Schematron :)

**Comment by ingofrank** [comment]
It is my fault: I forgot to provide the appropriate Schematron schema for testing purposes to my colleague Konrad.

Please find enclosed the ZIP file containing the schema which has the needed rules:

[hsp_test.zip](https://github.com/phax/ph-schematron/files/12067402/hsp_test.zip)

Sorry for the confusion.

The small Schematron schema in the ZIP file includes also some diagnostic elements for more human-readable validation messages, which the Schematron schema generated from the TEI ODD does not (yet) include.

Here for example is the rule to test the `@role` and `@ref` attributes of person entries:

```
   <pattern id="persNameRef">
      <rule role="error" context="tei:persName/@ref">
         <assert test="matches(., '^https?://d-nb.info/gnd/')" diagnostics="d_ref_en d_ref_de">@ref requires a GND URI. '<value-of select="."/>' is not a valid GND URI.</assert>
      </rule>
   </pattern>
```

**Comment by phax** [comment]
Okay, if I use this Schematron on the test file, I get 2 failed assertions:
1.
```xml
  <svrl:failed-assert location="Autor" test=". = ('commissionedBy', 'author', 'bookbinder', 'mentionedIn', 'scribe', 'previousOwner', 'translator', 'illuminator', 'conservator', 'other', 'complementedBy', 'editedBy')">
    <svrl:text>@role requires a label from the controlled vocabulary for person roles. 'Autor' is not an entry from the controlled vocabulary.</svrl:text>
    <svrl:diagnostic-reference diagnostic="d_role_en" xml:lang="en">
If given the role of a person must be an entry from the controlled vocabulary providing the possible roles of persons! -- The role attribute 'Autor' in element persName is not an entry from the controlled vocabulary.</svrl:diagnostic-reference>
    <svrl:diagnostic-reference diagnostic="d_role_de" xml:lang="de">
Wenn angegeben, braucht das role-Attribut einer Person einen Eintrag aus dem kontrollierten Vokabular für die möglichen Rollen von Personen! -- Das role-Attribut im Element persName ist mit 'Autor' kein Eintrag aus dem kontrollierten Vokabular.</svrl:diagnostic-reference>
  </svrl:failed-assert>
```

and 2.

```xml
  <svrl:failed-assert location="" test="matches(., '^https?://d-nb.info/gnd/')">
    <svrl:text>@ref requires a GND URI. '' is not a valid GND URI.</svrl:text>
    <svrl:diagnostic-reference diagnostic="d_ref_en" xml:lang="en">
A person's ref attribute must link to a GND URI! -- The entry '' of the ref attribute of the persName element is not a valid GND URI.</svrl:diagnostic-reference>
    <svrl:diagnostic-reference diagnostic="d_ref_de" xml:lang="de">
Das ref-Attribut einer Person muss eine GND-URI enthalten! -- Im ref-Attribut des Elements persName ist mit '' keine gültige GND-URI eingetragen.</svrl:diagnostic-reference>
  </svrl:failed-assert>
```

**Comment by KonradEichstaedt** [comment]
@phax Many thanks for your great and fast support. The implementation above shows with the proper schematron file to expected errors. Because of this I would say again many thanks and close the issue.

**Comment by phax** [comment]
@KonradEichstaedt thanks for the update and greetings from Vienna :)
