### ISSUE TITLE
External Doc support in schematron

### ISSUE THREAD

**Issue by pradyumanaggarwal** [phax/ph-schematron#161]
Does ph-schematron provide any external doc support where users can write variable values and use it inside sch files. 
For example : 

`<sch:let name="Id" value = "document('config.xml')"`

If yes, then can you share any documentation on how to use this and which ph-schematron implementation can be used to do so.

Thanks

**Comment by phax** [comment]
Yes, that can be done and requires the ISO Schematron or SchXslt implementation - it does not work with the "pure" implementation, because `document` is an XSLT feature. Unfortunately I couldn't find a working example but it has been successfully used in the past

**Comment by pradyumanaggarwal** [comment]
Is there any documentation or anything that I can refer to on how to use external documents ?

**Comment by phax** [comment]
Well you should search for XSLT documentation on it. E.g. https://stackoverflow.com/questions/61149268/how-does-the-document-function-work-in-xslt might help.
hth

**Comment by pradyumanaggarwal** [comment]
But still the question remains 
`final ISchematronResource schemaResource = SchematronResourceSCH.fromFile(this.schematronFile);`

here if we are not passing any external file, then how will that work using `select="document('abc.xsml')"`

Thanks anyways.

**Comment by phax** [comment]
I pushed an example for you that shows how to use document. Please note that the filepaths need to be adopted

**Comment by phax** [comment]
@pradyumanaggarwal  did that solve your issues? If so, feel free to close the ticket - thanks
