### ISSUE TITLE
Variables in let/@value are not replaced in abstract patterns 

### ISSUE THREAD

**Issue by silentbang** [phax/ph-schematron#17]
As I try with the latest PHSchematron version, there's still the problem as discussed at:
https://github.com/Schematron/schematron/issues/6
Has anyone done anything to fix this?

**Comment by phax** [comment]
Im on vacation. Will look at it when Im back

**Comment by phax** [comment]
Okay, proposed changes have been integrated :)

**Comment by jkiddo** [comment]
I'm experiencing this issue as of release 4.2.1
