### ISSUE TITLE
Issue with Error Handling in XSLT Mode vs PURE Mode

### ISSUE THREAD

**Issue by gediminasre** [phax/ph-schematron#180]
Hello @phax,

I wasn’t able to reopen [issue #171](https://github.com/phax/ph-schematron/issues/171), so I’m creating this new one instead.

We’ve just had the chance to test the fix, and it seems that the issue persists. In the [8.0.1 release](https://github.com/phax/ph-schematron/releases/tag/ph-schematron-parent-pom-8.0.1), you mentioned:

    "Improved the error handling in 'pure' mode."

However, the problem we’re encountering is actually in XSLT mode. There may have been some confusion regarding which mode required the fix.

Would you kindly take another look at this? We really appreciate your efforts!

To clarify:

    PURE mode: ✅
    XSLT mode: ❌

Thank you in advance!

**Comment by gediminasre** [comment]
Hello @phax, any change you can have a look at the issue?

**Comment by phax** [comment]
@gediminasre Well, unfortunately the ISO Schematron XSLT rules are provided by an external source, so there is not much I can do. And I am not enough of an XSLT expert to add the respective changes to the (officially discontinued) ISO Schematron XSLTs - sorry.

**Comment by gediminasre** [comment]
Thank you for your answer. Closing the issue.
