### ISSUE TITLE
Thread safety issue for variable values with ph-schematron-pure 8.0.3

### ISSUE THREAD

**Issue by bertrand-lorentz** [phax/ph-schematron#182]
In the Schematron rules we use, a variable is defined at the top level and stores a value for the XML being validated:
```XML
<let name="noticeSubType" value="/*/ext:UBLExtensions/.../cbc:SubTypeCode/text()"/>
```

It is then used in lots of rule contexts:
```XML
<rule context="/*[$noticeSubType = '1']">
...
<rule context="/*[$noticeSubType = '2']">
...
<rule context="/*/cac:ContractingParty[$noticeSubType = '1']">
...
<rule context="/*/cac:ContractingParty[$noticeSubType = '2']">
```

When validating XML files in separate threads, the value of this variable is sometimes changed during the validation of an XML file.
This is visible in the SVRL, which shows that rules for other values are fired (simplified example):

```XML
<?xml version="1.0" encoding="UTF-8"?>
<svrl:schematron-output xmlns:svrl="http://purl.oclc.org/dsdl/svrl" title="eForms schematron rules">
. . .
    <svrl:fired-rule context="/*[$noticeSubType = '1']" />
    <svrl:fired-rule context="/*/cac:ContractingParty[$noticeSubType = '2']" />
. . .
```
This only happens when the application is under load (in production...): concurrent requests to validate different XML that have different values for the variable.

Here's what I think is happening:
1/ During the bind part, a single instance of `XPathLetVariableResolver` is created, and kept in the `PSXPathBoundSchema ` object
2/ ThreadA starts validating an XML: variables are evaluated and their value stored in `XPathLetVariableResolver`, and some rules are executed
3/ ThreadB starts validating another XML: variables are evaluated and their value stored in the same `XPathLetVariableResolver`, overwriting the values set by ThreadA
4/ ThreadA executes rules that reference variables, so uses the values set by ThreadB.

My first idea is to make [the map that stores variable values](https://github.com/phax/ph-schematron/blob/master/ph-schematron-pure/src/main/java/com/helger/schematron/pure/xpath/XPathLetVariableResolver.java#L33) ThreadLocal.
But I guess that first we need a way to reproduce the problem reliably...

Any help or suggestions are welcome !

**Comment by phax** [comment]
Thanks @bertrand-lorentz  for the fix. I took it over as-is, and it will be included in the 8.0.4 release
