### ISSUE TITLE
IllegalAccessError during XPathFactory creation disrupting application

### ISSUE THREAD

**Issue by fls4507** [phax/ph-schematron#19]
Hello,

I am encountering an issue with version 3.0.1 when attempting to check if a file is valid pure xpath schematron. During the creation of the XPathFactory in `PSXPathBoundSchema.createXPathFactorySaxonFirst()`, the first attempt to create the xpath factory is failing with an `java.lang.IllegalAccessError` which, unfortunately, is a type of `Throwable` and not an `Exception`. Due to this, the catch block in the same method does not catch the Throwable and execution passes back up to the finally block in   `AbstractNotifyingCache.getFromCache()`.

This is the error text: 
> tried to access method javax.xml.xpath.XPathFactoryFinder.createInstance(Ljava/lang/String;)Ljavax/xml/xpath/XPathFactory; from class javax.xml.xpath.XPathFactory

This probably stems from using Xalan's xpath implementation extensively throughout the rest of my project. Are you aware of any workarounds or other options for resolving this issue?

**Comment by phax** [comment]
I see your problem. What Java version are you using? Do you need a 3.0.2 backport or can you wait a couple of days until 4.0.0 for JDK 8 is out?

**Comment by fls4507** [comment]
Thanks for the quick reply!
I don't foresee a problem with waiting for version 4.0.0.

**Comment by phax** [comment]
4.0.0 is on its way to Maven Central
