### ISSUE TITLE
Generated xslt doesn't have namepsace definitions

### ISSUE THREAD

**Issue by baerrach** [phax/ph-schematron#25]
When I run the resulting xslt against the xml to check I get the error:
```
10:20:20,001 ERROR [main] JAXPSAXProcessorInvoker  - Undeclared namespace prefix {ex}; SystemID: file:/path/src/main/xslt/check-classifications.xslt; Line#: 222; Column#: 85
; SystemID: file:/path/src/main/xslt/check-classifications.xslt; Line#: 222; Column#: 85
```

I'm using example05 from http://www.xfront.com/schematron/license.html located in their zip file at schematron\examples\example05\

The only other thing I can find on the internet is this unanswered stackoverflow question

http://stackoverflow.com/questions/32784781/ph-schematron-namespace-prefix-error-after-compiling-schematron-to-xslt-using-p

http://www.schematron.com/ shows the steps that the software under the hood takes, which is the same step process that ph-schematron does. I've also compared the files in your distribution against the default implementation and there is only one non-whitespace difference which you have commented that says  in iso_schematron_skeleton_for_saxon.xsl

SchematronProviderXSLTFromSCH.SAVE_INTERMEDIATE_FILES is set to false and has no capability to set to true other than rebuilding (I'll do that in a minute).

When I compare the final output of the www.schematron.com with the ph-schematron version I notice that the output differs; there is no default namespace, there are no namespace prefixes defined.

### www.schematron.com
```
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:schold="http://www.ascc.net/xml/schematron"
                xmlns:iso="http://purl.oclc.org/dsdl/schematron"
                xmlns:xhtml="http://www.w3.org/1999/xhtml"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:ex="http://www.example.org"
                version="1.0"><!--Implementers: please note that overriding process-prolog or process-root is 
```

### the ph-schematron
```
<stylesheet version="1.0" xmlns="http://www.w3.org/1999/XSL/Transform">
```

I'm in the process now of tracking this down. But thought I would post first in case you already know where I should look :)

**Comment by phax** [comment]
You can see in example 5 that they are not using ISO Schematron but some predecessor version. It is easily spottable through the namespace URI `http://www.ascc.net/xml/schematron` which is not ISO. ISO Schematron uses the namespace URI `http://purl.oclc.org/dsdl/schematron`.

**Comment by baerrach** [comment]
I coudn't find where I got example 5 from, and that was the closest hit I got.
The version I am using has the correct namespace "http://purl.oclc.org/dsdl/schematron", the rest of the file looks correct.

So far, it looks like a difference between how `net.sf.saxon.Transform` and `XMLTransformerFactory.createTransformerFactory()` setups up the Transform.

I suspect its a missing option to output namespaces.

**Comment by baerrach** [comment]
Bah! Trawling through saxon is like rolling around in an ant hill covered in honey.
I'm yet to find the difference between the two. Try again tomorrow.

**Comment by phax** [comment]
I took the example 5, changed the namespace URI and here's my minified SCH using XSLT:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<schema xmlns="http://purl.oclc.org/dsdl/schematron">
   <ns prefix="ex" uri="http://www.example.org" />
   <pattern name="Security Classification Policy">
      <p>A Para's classification value cannot be more sensitive 
         than the Document's classification value.</p> 
      <rule context="ex:Para[@classification='top-secret']">
         <assert test="/ex:Document/@classification='top-secret'">
             If there is a Para labeled "top-secret" then the Document  
             should be labeled top-secret
         </assert>
      </rule>
      <rule context="ex:Para[@classification='secret']">
         <assert test="(/ex:Document/@classification='top-secret') or                            (/ex:Document/@classification='secret')">
             If there is a Para labeled "secret" then the Document  
             should be labeled either secret or top-secret
         </assert>
      </rule>
      <rule context="ex:Para[@classification='confidential']">
         <assert test="(/ex:Document/@classification='top-secret') or                            (/ex:Document/@classification='secret') or                             (/ex:Document/@classification='confidential')">
             If there is a Para labeled "confidential" then the Document  
             should be labeled either confidential, secret or top-secret
         </assert>
      </rule>
   </pattern>
</schema>
```
which looks okay to me. The created SVRL is:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<schematron-output title="" schemaVersion="" xmlns="http://purl.oclc.org/dsdl/svrl">
    <ns-prefix-in-attribute-values prefix="ex" uri="http://www.example.org"/>
    <active-pattern document=""/>
    <fired-rule context="ex:Para[@classification='confidential']"/>
    <fired-rule context="ex:Para[@classification='secret']"/>
</schematron-output>
```
The problem is, that the created XSLT tries to create PCDATA content into the `active-pattern` element which is against the rules of the SVRL.

**Comment by phax** [comment]
And btw. if you would use the Pure version, it should work and you would spare the XSLT mess...

**Comment by phax** [comment]
So did you progress?

**Comment by baerrach** [comment]
Yes I have.

But its a bit messy at the moment, and its knock off time now so I will work on it some more tomorrow.

The short answer is that your XMLSerializer doesn't output namespaces.
I haven't written a test case yet for the pure option.

When I'm done you will have test cases showing you the different options and which ones work (or don't)

**Comment by phax** [comment]
My XMLSerializer does indeed emit namespaces :) If you send me your Schematron per email (see the pom.xml) I might have an easy solution for this... But as you like :)

**Comment by baerrach** [comment]
I've submitted a PR with the code to show what I expect should happen, and what is not happening.

Let me know if there is something simple I have overlooked.

**Comment by phax** [comment]
I reworked the folder paths a bit, so that it fits in the regular Maven structure and added namespace prefix mappings so that outputs are more comparable.
But the outcome is the same :) So there should be no difference (except attribute order in XSLT)

**Comment by baerrach** [comment]
As XML, by definition, doesn't specify attribute order (even if that is a pain for automated testing...) I would be happy with that outcome.

**Comment by phax** [comment]
Than just crosscheck, but my changes should not do anything to the output of the XSLT transformation.

**Comment by baerrach** [comment]
I see what you've done.

I guess I was expecting "magic" to happen and not have to defined the namespaces. At least the XLST one does something like that for me.

I will add the test xml files as well. (they are part of the example package I mentioned previously).

If you run the xslt generated you will get errors because the "ex" namespace doesn't exist. Hence the desire to have the magic happen.

**Comment by phax** [comment]
Yes please add the XML files for clarity. The namespaces in the XSLT are not used, that's why they are not emitted.

**Comment by phax** [comment]
I think I know what you meant and add an appropriate fix. Please check if that solves your issue

**Comment by baerrach** [comment]
Yes that fixes it.

**Comment by phax** [comment]
Thanks for verifying - I'm building a 4.0.1 release now!

**Comment by baerrach** [comment]
I cant find another way to send you a message, so I'll leave it here.

I was going to try to fix the indenting, but the HTML tests made my changes fail.

There is no way to fix that without extensive rewriting of the indentation engine. So I'm going to give up, and live with slightly ugly output - but at least working output.

Thanks.

**Comment by phax** [comment]
In the pom.xml you find my email address :)
If you want, I can switch the output engine to the regular DocumentBuilder output - for the plugin it is no big deal. It's optimized for self-constructed XMLs and is much quicker than the regular one.
