### ISSUE TITLE
Unable to use in OSGI Container

### ISSUE THREAD

**Issue by fls4507** [phax/ph-schematron#28]
Hello!

Can the library be used in OSGi containers? (like Apache Felix or Apache Karaf)
I noticed the libraries are bundled so I tried using the createXML in SVRLWriter in a project that runs inside Karaf.
The following exception was thrown when the JAXB Context was created:

```
Failed to create JAXB context for package 'org.oclc.purl.dsdl.svrl' using
ClassLoader BundleDelegatingClassLoader(com.foo.myclass [bundleID])
```

Overall this is very similar to an issue on another project, https://github.com/phax/ph-ubl/issues/4

I found a workaround by importing the org.oclc.purl.dsdl.svrl package in the bundle manifest of my com.foo.myclass package. This allows me to get past the JAXBContext error, but I am still encountering the next issue mentioned,  `IllegalStateException: Failed to open input stream for [cpPath=schemas/svrl.xsd; urlResolved=true; URL=null]`

I think the fix performed for the issue linked might be helpful on this schematron project as the error messages are so similar

**Comment by phax** [comment]
Hi!
What version are you using?
In 4.0.1 I checked the manifest and the `org.oclc.purl.dsdl.svrl` package is exported and imported.
Try using class `SVRLMarshaller` directly (instead of `SVRLWriter`). It offers methods to specify the classloader etc.
hth, Philip

**Comment by fls4507** [comment]
Sorry for the delay, tasking switched.
We are using version 3.0.1.
I believe the 3.0.1 version also has the dependencies you mention. I was saying I added the dependency to my module to skirt the Jaxb context exception, but my workaround doesnt solve the following issue.
 I'll be working on this the next week
Thanks, Josh

**Comment by fls4507** [comment]
Issue #29 looks very similar and has more progress. Voting to close and follow that

**Comment by phax** [comment]
Ok. So please also try 4.0.2 :)

**Comment by phax** [comment]
Are you using Wildfly for your application?
