### ISSUE TITLE
Unable to validate an xml file

### ISSUE THREAD

**Issue by saviour1108** [phax/ph-schematron#29]
[ph-schematron error.txt](https://github.com/phax/ph-schematron/files/363057/ph-schematron.error.txt)
Hi ,

I'm getting the above error while trying to validate a file. Could you help?
I'm using the latest version 4.0.1, please do let me know what else you need to invstigate

Thanks

**Comment by phax** [comment]
Hi!
I think this is a classloader issue when running in an OSGI environment.
Can you please point me/show me the source artefact where you are calling this.
Maybe you need to manually use class `SVRLMarshaller` and call `setClassLoader` on it.
hth, Philip

**Comment by phax** [comment]
Please look at the details of the commit.
I created a simple test file where I'm using a special classloader - please check if that fits your needs.
// Philip

**Comment by saviour1108** [comment]
Thanks for the detailed explanation, but using that code I've encountered some more exceptions.

I've attached the file.. 
[exception.txt](https://github.com/phax/ph-schematron/files/368192/exception.txt)

**Comment by phax** [comment]
Now it gets complicated: looks like I need to add some metadata as described in http://blog.osgi.org/2013/02/javautilserviceloader-in-osgi.html

**Comment by saviour1108** [comment]
I'm only getting the exception the first time around.. Does that information help?

**Comment by phax** [comment]
SPI initialization fails and is obviously not re-attempted. But that means that certain functionality may not work as expected...

**Comment by saviour1108** [comment]
Okay. Can you be specific, on what functionality may be affected?

**Comment by phax** [comment]
I may need to build a new version of ph-commons with additional OSGI packaging instructions

**Comment by saviour1108** [comment]
Okay. Thanks, could you point me in direction, where i would be able to proceed. I can handle the SPI exception and still proceed to validate.. Just wondering if doing this would result in application producing unexpected results

**Comment by phax** [comment]
Maybe. This class provides SPI `equals` implementations for stuff like `URL`, `BigDecimal` etc.

**Comment by saviour1108** [comment]
That worries me :|

**Comment by saviour1108** [comment]
When would you be pushing out a new build?

**Comment by phax** [comment]
Once I solved the problem :) Are you able to test with SNAPSHOT builds?

**Comment by saviour1108** [comment]
Yes, I can.

**Comment by phax** [comment]
So please test the latest ph-schematron 4.0.2-Snapshot. It is linked to ph-commins snapshot with osgi serviceLoader statements.

**Comment by saviour1108** [comment]
I'll give it a try today and get back to you

**Comment by saviour1108** [comment]
I tried downloading the snapshot version as recommended, doesn't seem to work on intellJ. But I've tried validating with version 4.0.0 and apart from the SPI initialization exception, the validator works fine. I am able to get consistent results. Can i suppress that exception somehow?

**Comment by phax** [comment]
If you have a Maven project, simply reference version `4.0.2-SNAPSHOT` of ph-schematron and it should work. Otherwise try downloading from https://oss.sonatype.org/content/repositories/snapshots/com/helger/ph-schematron/4.0.2-SNAPSHOT/
You also need ph-commons, ph-jaxb and ph-xml from the same server (version 8.2.2-SNAPSHOT)
hth

**Comment by saviour1108** [comment]
![image](https://cloud.githubusercontent.com/assets/10572812/17048860/83e019d2-502c-11e6-821d-972ef59634cf.png)
I tried the following set, and i'm getting the below exception.. 

 ErrorLogger got passed FATAL error for request D2Bq_EHpRFbJuU - : Error handling WebService request See nested exception: 
	Could not initialize class com.helger.schematron.xslt.SchematronResourceSCH

**Comment by phax** [comment]
Seems like something was cut off the previous message....
Except for xerces 2.4 which is really (!) old and that the ph-schematron-sources does not match the ph-schematron version it looks okay. What build system are you using?

**Comment by saviour1108** [comment]
Yeah, I removed the Xerces and the sources jar. I downloaded the 4.0.2 snapshot version from the server you provided. Now i'm back to  4.0.0
![image](https://cloud.githubusercontent.com/assets/10572812/17049130/983da064-502e-11e6-83a1-ea5ea16f9ef6.png)

**Comment by phax** [comment]
Okay, I will release ph-commons and ph-schematron on a "guess" basis and we will see what happens :)

**Comment by phax** [comment]
Please use ph-schematron 4.0.2, ph-commons 8.2.2, ph-xml 8.2.2 and ph-jaxb 8.2.2 - all are on Maven central now

**Comment by saviour1108** [comment]
Hi Phillip,
[SPI initialization error.txt](https://github.com/phax/ph-schematron/files/380550/SPI.initialization.error.txt)
 tried the 4.0.2 still getting the same initialization error. Logs attached. 

Thanks

**Comment by phax** [comment]
Okay, what OSGI container and what container version are you using?
Can you paste a basic setup so that I can test myself?
Thanks, Philip

**Comment by phax** [comment]
If this is too sensitive to paste here, you can my email address in pom.xml and may send me a PM...

**Comment by saviour1108** [comment]
Hi Sorry I had dropped off earlier, the project had gone on hold for a bit. I'm  now continuing with the project and seeing that i'm getting a new set of problem with validation. The application is running out of heapspace and getting the following as the console logs. Bear in mind that my xml would be close to 200mb and my heapsize is 3gb.
Please see attached file for the logs. 
[SchematronErrors.txt](https://github.com/phax/ph-schematron/files/458217/SchematronErrors.txt)

**Comment by phax** [comment]
The log you are sending is just about the beautification of error messages occurring in SVRL. And this shows, that you have `GlobalDebug.isDebugMode ()` enabled - this is not a performance boost. You may consider to globally call `GlobalDebug.setDebugModeDirect(false)` on startup to disabled some checks and logging (or you may want to implement an `ISVRLLocationBeautifierSPI` for your namespace).
Unfortunately I cannot find any OutOfMemory exception or the like in the logs :(

**Comment by aarora11** [comment]
Did a bit of debugging, its validating the xml but when trying to extract the failed assert list, its running out of heap. 

 final List<SVRLFailedAssert> failedList = SVRLHelper.getAllFailedAssertions(lSchematronOutput);

Is there any other way I can go about this?

**Comment by aarora11** [comment]
I am validating an validating a 200mb xml file which has lSchematronOutput.getActivePatternAndFiredRuleAndFailedAssert() size as 1384095. I know this is a lot of errors but I'm catering for a worst case scenario. Can you help me optimize the code for such scenarios?

**Comment by phax** [comment]
If you send me the file, it would be highly appreciated (plus the rules). I will handle it confidential of course.
My email address can be found inside pom.xml

**Comment by phax** [comment]
Thanks, got the mail and will look at it when I find time :)

**Comment by aarora11** [comment]
Hi Philip

Any luck with the issue?

Kind Regards

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by phax** [comment]
I think the process can be speed up, when using the pure implementation.
That on the other hand would require implementation of the "key" function as part of the pure Schematron stuff. So on the one hand parsing all "xsl:key" elements and on the other hand implementing the "key" function and passing into Saxon (custom function definition).
Can you help with this as my time is quite limited at the moment???

**Comment by aarora11** [comment]
Yes sure. How would you like to proceed?

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by phax** [comment]
1. I need to add a way to handle elements from differen xml namespaces
2. Implement a map from name to nodelist containing all the declared keys
3. Implement a key function, resolve objects from the map retrieved in step 2 and return the matching node
Does thatsound reasonable to you?
