### ISSUE TITLE
id's are null when read from result

### ISSUE THREAD

**Issue by jkiddo** [phax/ph-schematron#31]
The result objects of type FailedAssert when traversing  org.oclc.purl.dsdl.svrl.SchematronOutputType.getActivePatternAndFiredRuleAndFailedAssert() has the id field set to null

**Comment by phax** [comment]
Hi! Sorry for delay - we had a public holiday.
The "id" is only set if the source assert/report has an "id" set. Otherwise this optional attribute is not emitted.
