### ISSUE TITLE
Does schematron support validation across xml files

### ISSUE THREAD

**Issue by vinayshivanna** [phax/ph-schematron#32]
I am a new bee to schematron and evaluating it to use it in one of my project. I have specific usecase where i have particular element in xml1 with certain value and the same value should be associated with one more element in xml2. Let me know if this can be validated through schematron. At present if it is not available then how do i extend to implement the functionality. 
Ex
xml1
```
<items>
   <item value="oneitem"></a>
</items>
```

xml2
```
<all>
   <b item_names="checkout checkout1 checkout2"/>
</all>
```

This is an existing app and i don't have provision to change it.

**Comment by phax** [comment]
I think there is an XSLT function "document" that might help you. Please have a look in this direction.

**Comment by vinayshivanna** [comment]
Is there a pure java implementation for the same ? My previous experiences with XSLT was bad with respect to big XML.

**Comment by phax** [comment]
Currently no. The pure implementation can only handle XPath - but no more. I thought about implementing xsl:key - but not xsl:document. Any help is appreciated :)

**Comment by vinayshivanna** [comment]
Sure. Once i get fair idea i will contribute.

**Comment by mhguruprasad** [comment]
Hi, I went through your article. Very nice. I am trying to run this as maven project. pls advise.

**Comment by phax** [comment]
No prob. What exactly do you want to know besides https://github.com/phax/ph-schematron#ph-sch2xslt-maven-plugin ?
Maybe you can create a separate issue for this? Thanks :)

**Comment by mhguruprasad** [comment]
Thanks. I am able convert schematron to XSLT. Please let me know how we can validate this with XML document. Which project/file I need to use.

**Comment by phax** [comment]
The Maven plugin can only convert SCH to XSLT.
It currently does **not** support validating XML documents.
Is this really needed?

**Comment by mhguruprasad** [comment]
Yes. we need to validate XML documents.

**Comment by phax** [comment]
I've created a new issue for this, because this is something new. Please follow up the discussion there.
