### ISSUE TITLE
Create maven plugin to validate XML files with Schematron

### ISSUE THREAD

**Issue by phax** [phax/ph-schematron#33]
As requested by https://github.com/mhguruprasad in https://github.com/phax/ph-schematron/issues/32#issuecomment-265044322

**Comment by phax** [comment]
Input parameters needed:
  * Schematron file path (mandatory)
  * XML file path (mandatory)
  * Implementation to use (XSLT or pure) (optional; default pure)
  * SVRL file path (optional) - if set, the SVRL is written there

The build will fail, if the validation fails.
Anything else?

**Comment by mhguruprasad** [comment]
Nothing else. Just ran the project and getting compilation errors. Pass me once done. Thanks.

**Comment by phax** [comment]
It's work in progress - not finished yet :) I do it only in my sparetime....

**Comment by mhguruprasad** [comment]
Fine. Thanks.

**Comment by phax** [comment]
The initial version is finally in the repo and working so far. I will now create some docs for it.

**Comment by phax** [comment]
Please check at https://github.com/phax/ph-schematron#ph-schematron-maven-plugin

**Comment by phax** [comment]
Published as 4.2.0

**Comment by navjottiwana** [comment]
I am trying to analyze 20 xml files with a single .sch rules using schematron maven plugin. The build is failing at 3rd xml file. I want schematron to analyze all 20 xml files and then fail the build. Can you please suggest.
