### ISSUE TITLE
Picking up variables in 'let' schematron statements

### ISSUE THREAD

**Issue by jkiddo** [phax/ph-schematron#36]
It seems that the declared variables in 'let statements' are not picked up and exploded in the 'assert statements'

**Comment by phax** [comment]
Referring to issue #17 - right?
Can you please paste an example here - thanks.

**Comment by jonigkeit** [comment]
The problem is with abstract rules

Example schematron
`<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://purl.oclc.org/dsdl/schematron">
    <pattern>
    		<rule abstract="true" id="ABSTRACT">
    		<let name="roat" value="'roat'"/>
    		<let name="root" value="'root'"/>
    		<let name="rootRef" value="$root"/>
    		<assert role="error" test="matches($roat,@value)">@value must be abstract $roat</assert> 
    		<assert role="error" test="matches($root,@value)">@value must be abstract $root</assert> 
    		<assert role="error" test="matches($rootRef,@value)">@value must be abstract $rootRef</assert> 
    		<assert role="error" test="matches('root',@value)">@value must be abstract root</assert> 
	    	</rule>
	    	
    		<rule context="root" id="CONCRETE">
    		<let name="roat" value="'roat'"/>
    		<let name="root" value="'root'"/>
    		<let name="rootRef" value="$root"/>
    		<assert role="error" test="matches($roat,@value)">@value must be concrete $roat</assert> 
    		<assert role="error" test="matches($root,@value)">@value must be concrete $root</assert> 
    		<assert role="error" test="matches($rootRef,@value)">@value must be concrete $rootRef</assert> 
    		<assert role="error" test="matches('root',@value)">@value must be concrete root</assert> 
	    	</rule>

	    	<rule context="root">
	    	<extends rule="ABSTRACT"/>
	    	</rule>
    </pattern>
</schema>`

Example XML
`<root value="root"/>`

**Comment by jonigkeit** [comment]
Here is a simpler version

```xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://purl.oclc.org/dsdl/schematron">
	<pattern>
    	<rule abstract="true" id="my-abstract-rule">
    		<let name="my-root-variable" value="'root'"/>
    		<assert role="error" test="$my-root-variable = @value">@value must be 'root'</assert>
	    </rule>
	    	
	    <rule context="root">
	    	<extends rule="my-abstract-rule"/>
	    </rule>
    </pattern>
</schema>
```

```xml
<root value="root"/>
```

**Comment by phax** [comment]
It's a problem with the pure implementation... working on it

**Comment by phax** [comment]
Now also works in "pure" version

**Comment by phax** [comment]
Release 4.2.2. should be on Maven central within the next hour
