### ISSUE TITLE
ph-schematron-maven-plugin: xmlDirectory with subdirectory structure breaks SVRL export

### ISSUE THREAD

**Issue by philippn** [phax/ph-schematron#37]
Hiya,

when pointing xmlDirectory to a directory that includes a directory structure with XML files, outputting the SVRL files using the `svrlDirectory` parameter does not work. It breaks with `FileNotFoundException` because the directories are non-existant in the `svrlDirectory`.

A simple solution is to add:
```
aSVRLFile.getParentFile().mkdirs();
```

directly after
```
// Save SVRL
final File aSVRLFile = new File (svrlDirectory, sXMLFilename + ".svrl");
```

Thanks in advance and kind regards,
Philipp

**Comment by phax** [comment]
Thx for pointing this out - pretty straight forward solution :)
