### ISSUE TITLE
doc or document feature request

### ISSUE THREAD

**Issue by jkiddo** [phax/ph-schematron#41]
Is there any chance that the issue listed here (https://saxonica.plan.io/issues/3213?pn=1#change-8364) could be fixed in this framework, by replacing 'document' to 'doc' when doing pure SVRL validation - perhaps as a configuration parameter?

**Comment by phax** [comment]
Reminder to myself: http://stackoverflow.com/questions/37359555/what-is-the-difference-of-document-and-fndoc-in-xslt

**Comment by phax** [comment]
@jkiddo Can you please paste an example Schematron - I'm currently short on time :) Thanks

**Comment by ahenket** [comment]
`<assert role="error" see="http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.107" test="count(hl7:administrativeGenderCode[concat(@code,@codeSystem)=document('include/voc-2.16.840.1.113883.1.11.1-DYNAMIC.xml')//valueSet[1]/conceptList/concept/concat(@code,@codeSystem)][not(@nullFlavor)])&gt;=1">(DKAlternativelyIdentifiedPatientRole): element hl7:administrativeGenderCode[concat(@code,@codeSystem)=document('include/voc-2.16.840.1.113883.1.11.1-DYNAMIC.xml')//valueSet[1]/conceptList/concept/concat(@code,@codeSystem)][not(@nullFlavor)] is mandatory [min 1x].</assert>`

**Comment by phax** [comment]
So by switching from "Pure" to "SCH" implementation this can be resolved.
