### ISSUE TITLE
Rules with | in context

### ISSUE THREAD

**Issue by philippn** [phax/ph-schematron#44]
Hi Philip,
I have noticed that when I setup a rule like

`<sch:rule context="th[@data-role = 'interval'] | td[@data-role = ('interval', 'task')]">`

the rule isn't fired anymore. When I make two rules out of this, it works.
I do believe that the usage of | is supported in the standard, and it also works in Oxygen.

Thanks in advance and kind regards,
Philipp

**Comment by phax** [comment]
Hi Philipp :)
Are you using the "Pure" or the "XSLT" based version?
Try the XSLT one please.
// Philip

**Comment by philippn** [comment]
Hi Philip,
I'm not quite sure what you mean? I'm using the maven-plugin, the configuration property <schematronProcessingEngine>is not set. When I set it to xslt or schematron, it makes no difference though

**Comment by phax** [comment]
Okay - thanks for the clarification - will check.

**Comment by phax** [comment]
I can confirm, that the `|` operator behaves different, depending on whether you are using the "pure" implementation (XPath in Java) compared to the XSLT based version (convert Schematron with the help of XSLT to XSLT and than applying this to XML).

So please see https://github.com/phax/ph-schematron/blob/master/ph-schematron/src/test/java/com/helger/schematron/supplementary/Issue44Test.java#L42 compared to https://github.com/phax/ph-schematron/blob/master/ph-schematron/src/test/java/com/helger/schematron/supplementary/Issue44Test.java#L44 

hth

**Comment by phax** [comment]
Any update??

**Comment by philippn** [comment]
Hi Philip, 
sorry, for the late reply. I'm not quite sure what to make out of your comment to be honest. 

You are saying that it works when using XSLT based processing and with pure it doesn't. I would have guessed so because it works in Oxygen and I assume that they do the XSLT stuff in the background. Isn't the whole point of the pure implementation to match the feature set of the XSLT implementation? If not, what else behaves differently? Are the differences documented somewhere?

**Comment by phax** [comment]
Hi Philipp,
yes I suggest to switch from "pure" to "sch" mode in the plugin.
The goal of the "pure" mode is to mimic "XPath" features but no XSLT.
hth
