### ISSUE TITLE
Rules failing with schematronProcessingEngine="pure"

### ISSUE THREAD

**Issue by fviolette** [phax/ph-schematron#47]
Hello,

Thanks for this lib!

The following assert/report expressions fail for me with the `pure` schematronProcessingEngine:

```xml
<sch:report test="node()[self::text()][matches(., '^\s')]" role="warning" sqf:fix="remove-leading-whitespace">
     The topic title must not start by a space.
</sch:report>
```

```xml
<sch:assert test="if (@xml:lang != 'en') then some $token in tokenize(base-uri(), '/') satisfies $token = @xml:lang else true()" role="fatal">
    The values of @xml:lang and the above language folder are not the same.
</sch:assert>
```

```
check.topic:
[schematron] Error in Schematron: [error] in PSAssertReport @ C:\git\documentati
on-dita\framework\rules\topic.sch Failed to compile XPath expression in <assert>
: 'if (@xml:lang != 'en') then some $token in tokenize(base-uri(), '/') satisfie
s $token = @xml:lang else true()' with the following variables: {} (javax.xml.xp
ath.XPathExpressionException: javax.xml.transform.TransformerException: Could no
t find function: if)
[schematron] Error in Schematron: [error] @ C:\git\documentation-dita\framework\
rules\topic.sch Error creating bound schema (java.lang.IllegalArgumentException:
 com.helger.schematron.pure.binding.SchematronBindException: Failed to precompil
e the supplied schema.)`
```

I haven't tested with schematron or xslt yet as per https://github.com/phax/ph-schematron/issues/45.

Thanks in advance for your support.

**Comment by phax** [comment]
Hi Francois, I created a test file and it works without problems.
Is it possible, that you have Xalan in your classpath, and that takes precedence????

**Comment by fviolette** [comment]
I don't think so but I will double-check tomorrow. I will also make a separate unit test for it, outside if my global file.
I thought it could be XSLT1 vs 2 but my declarations seem OK. For information, replacing matches with starts-with passed, though that's no longer the same test.

**Comment by fviolette** [comment]
Obviously a classpath issue. It's solved now - the work can begin :+1:

**Comment by fviolette** [comment]
Reopening because I suspect I have a setup issue again: some more patterns with `base-uri()` don't pass on my side (with `pure`). When printing out the error message if I include <sch:value-of select="base-uri()"/> nothing returns, unlike in oXygenXML. All other expressions in above samples and other random XPath 2.0 as well (current-dateTime(), avg(), upper-case(), etc.) are fine. Do you have an idea?

**Comment by fviolette** [comment]
Investigating... could this be linked: https://sourceforge.net/p/saxon/mailman/saxon-help/thread/loom.20130530T132624-669%40post.gmane.org/ (cf. answer)?

**Comment by phax** [comment]
`base-uri()` seems to be a very specific case :) I understand what goes wrong, but I couln't pinpoint this in the code so far. Will keep digging :)

**Comment by fviolette** [comment]
Super thanks :)

**Comment by fviolette** [comment]
Will the next snapshot be enough to test the fix?

**Comment by phax** [comment]
Yes. Just noticed that the Travis build failed - on it. Sorry.

**Comment by fviolette** [comment]
Oh don't! If that works, I am going to be the happiest man :-)

**Comment by phax** [comment]
SNAPSHOT -17 should (hopefully) do the trick. Hope to make you the happiest man :)

**Comment by fviolette** [comment]
It seems that the `base-uri()` returned is the Schematron's.

```
<sch:assert test="some $token in tokenize(base-uri(), '/') satisfies $token = @xml:lang" role="fatal">
     The values of @xml:lang and the above language folder are not the same
     (<sch:value-of select="base-uri()"/>)
</sch:assert>
```

```
[schematron] [error] in /concept @ C:\git\documentation-dita\development\configuration\en\c-configure_sap_to_operate_with_rfc.dita The values of @xml:lang and the above language folder are not the same (file:/C:/git/documentation-dita/framework/rules/temp/topic.sch)
```

**Comment by phax** [comment]
Sometimes I would appreciate if I would start thinking aforehead.... *sigh*

**Comment by fviolette** [comment]
SNAPSHOT -18 seals the deal :v: !

**Comment by xephon2** [comment]
@fviolette, I've updated [org.doctales.schematron](https://github.com/doctales/org.doctales.schematron) to use _SNAPSHOT 18_.

**Comment by fviolette** [comment]
Excellent - it's a long shot for me to use it, time to fix _content_ issues ;-)
@phax Issue can be closed as far as I am concerned.
