### ISSUE TITLE
SchematronTestHelper can not work

### ISSUE THREAD

**Issue by zhujiancom** [phax/ph-schematron#55]
I found Helger using new collection classes to find schematron testfiles, like below codes:
`private static final ICommonsList <SchematronTestFile> s_aSCHs = _readDI (new ClassPathResource ("test-sch/dirindex.xml"));`
but i didn't find dirindex.xml in resources folder, does someone lost put this file?

**Comment by phax** [comment]
There is a little preconfiguration needed to make this work. Running `mvn generate-resources` on the console should generate the files (using the ph-dirindex-maven-plugin). hth

**Comment by zhujiancom** [comment]
thank you ! i copy the dirindex.xml file to test-sch folder manually and
it's worked.

2017-10-30 14:43 GMT+08:00 Philip Helger <notifications@github.com>:

**Comment by phax** [comment]
Okay - seems like the setup is not 100% easy going - will look at it!

**Comment by phax** [comment]
Should work now; I disabled the plugin and instead added the files to the repository
