### ISSUE TITLE
XSLT functions called from assertions cause compile fail

### ISSUE THREAD

**Issue by fviolette** [phax/ph-schematron#59]
With preprocess or not, assertions that rely on custom XSLT functions will fail to compile.

In the same file:

```
<sch:ns prefix="foo" uri="http://foo/bar/baz"/>
```

```
<sch:pattern id="foo-pattern">
    <sch:rule context="prodinfo/module">
        <sch:assert test="foo:hasZ(.)"/>
    </sch:rule>
</sch:pattern>
```

```
<xsl:function name="foo:hasZ" as="xs:boolean">
     <xsl:param name="id" as="xs:string"/>
     <xsl:value-of select="contains($id, 'z')"/>
</xsl:function>
```

Log:
```
check.map:
[schematron] Error in Schematron: [error] in PSAssertReport @ C:\git\test.sch
Failed to compile XPath expression in <assert>:
'foo:hasZ(.)' with the following variables: {} (javax.xml.xpath.XPathExpressionE
xception: net.sf.saxon.trans.XPathException: Cannot find a 1-argument function n
amed {http://foo/bar/baz}hasZ())
[schematron] Error in Schematron: [error] @ C:\git\test.sch
Error creating bound schema (java.lang.IllegalArgumentException: c
om.helger.schematron.pure.binding.SchematronBindException: Failed to precompile
the supplied schema.)
[schematron] The provided Schematron file contains errors. See log for details.

```

I have other examples with nested function calls (utils).

**Comment by phax** [comment]
That is correct :)
You must provide the external functions somehow.
It looks like you are using the pure version - in this case you must provide a custom function resolver via `SchematronResourcePure.setFunctionResolver`

**Comment by phax** [comment]
Did you manage to get it working?

**Comment by fviolette** [comment]
I planned to move these functions to abstract patterns as much as possible but haven't had time to look into this yet. If you can point me to a sample file, I'll be trying this by next week.

**Comment by phax** [comment]
I see the problem. The custom function resolver is only available for the pure version but not for the SCH/XSLT based version. So I will try to find a solution for this on SCH/XSLT basis.

**Comment by phax** [comment]
Maybe you can include the XSLT functions from your SCH? https://github.com/Schematron/schematron/issues/42 might be in this direction?

**Comment by fviolette** [comment]
Using `pure` validation engine, with SCH containing `<xsl:function>`, `<xsl:param>` and one two `<xsl:template>` (which have worked so far without any issues). Removing them does not help but I am going to dig deeper.

Other than that, I've just tested the adapted sample from https://github.com/Schematron/schematron/issues/42 with `pure` engine again.

If I `<sch:value-of select="$test"/>`, I get:

```
[schematron] 1 Schematron error for XML file 'C:\git\documentation-dita\developm
ent\configuration\fr\dm-use_secured_kafka_studio.ditamap'
[schematron]   [error] in /map/title @ C:\git\documentation-dita\development\con
figuration\fr\dm-use_secured_kafka_studio.ditamap
Failed to compile XPath expression in <value-of>
: '$test' (javax.xml.xpath.XPathExpressionException: net.sf.saxon.trans.XPathExc
eption: Variable is used in XPath expression, but no JAXP VariableResolver is av
ailable)
```

Expected from your previous post if I understand correctly?

If I `<xsl value-of select="$test"/>`, I get a blank value:

```
[schematron] 1 Schematron error for XML file 'C:\git\documentation-dita\developm
ent\configuration\fr\dm-use_secured_kafka_studio.ditamap'
[schematron]   [error] in /map/title @ C:\git\documentation-dita\development\con
figuration\fr\dm-use_secured_kafka_studio.ditamap This rule will always fire, de
monstrating how XSLT instructions seem to be executed without problems in Schema
tron. For example, the named template "get.test" will execute the function "loca
l:get.test()" which will retrieve the value of the variable $test, namely: ''
```

**Comment by phax** [comment]
Well the pure implementation has a method `setVariableResolver` where you can provide an `javax.xml.xpath.XPathVariableResolver` - a map based implementation of this is available at `com.helger.xml.xpath.MapBasedXPathVariableResolver`

For the XSLT based version you can use `setParameters` and directly pass in a `Map<String,?>` which will be used to resolve custom parameters/values. A test is available for #8 - hth

**Comment by fviolette** [comment]
Thanks for your help, I am validating through ANT so the integration process sounds convoluted for me (given my lack of focus on tasks that use this project lately).
Can you briefly describe the steps which would be required to achieve this, sticking with ANT?

By the way, I have been able to get rid of my custom functions and implement my logic - we're looking into an RDF file - with and without abstract patterns, and it is working for me.

**Comment by fviolette** [comment]
Bumping just in case my edit wasn't seen - thanks!

**Comment by phax** [comment]
Unfortunately I currently don't have too much time for ph-schematron :(

**Comment by andreacaldeo** [comment]
nculuachitemmuartu

**Comment by phax** [comment]
Hi. Basically the `pure` version cannot be used as soon as XSLT is needed. Instead use the `sch` version only.
To pass in variables, we're again with issue #62 - right?

**Comment by fviolette** [comment]
Yes 👍 I'll catch up on this.

**Comment by phax** [comment]
@fviolette Even though it was a long time ago - do you know if I can close this one?

**Comment by fviolette** [comment]
Yes, no problem.
