### ISSUE TITLE
Inconsistent XPath interpreter?

### ISSUE THREAD

**Issue by R00dRallec** [phax/ph-schematron#6]
Hi, 

I'm currently struggeling with the XPath interpreter.
Do you use different ones?
In my main project, i get this exception:
javax.xml.transform.TransformerException: Could not find function: doc

In another project for testing other stuff (yeah i know JUnit in the same project would be better, need to change this) there is no exception for the function doc.

But if I use the function current() to refer to my context element, my main project is totally fine.

My testing project throws this exception: net.sf.saxon.trans.XPathException: Unknown system function curent()

I cant explain this. I'm using the same libraries in both projects. 
Versions:
ph-schematron 2.9.1
ph-commons 5.3.0
Saxon-He-9.6.0-4

Thanks in advance.

**Comment by phax** [comment]
Are you sure it "curent" and not "current" (with double "r")?
And in the other project, please check if you have also Xalan in your classpath.
Mixing Xalan and Saxon seems to be difficult.
Btw. are you referring to the following "doc" function: http://www.xsltfunctions.com/xsl/fn_doc.html ??
Or which one do you mean?

**Comment by R00dRallec** [comment]
I made a typo, but current with double "r" gives another error:
net.sf.saxon.trans.XPathException: System function current#0 is not available with this host language/version

Yes in my "main" project i have Xalan in my classpath, but not in the testing project.

**Comment by phax** [comment]
The problem with "current" is, that this is an XSLT function, but the pure Schematron implementation handles only XPath functions.
Maybe you find a matching XPath2 function that solves your problem????

**Comment by R00dRallec** [comment]
Okay, but why have I been able to use this function with your pure Schematron implementation before?
This is confusing, because the function worked once.

**Comment by R00dRallec** [comment]
According to this: http://de.selfhtml.org/xml/darstellung/xpathfunktionen.htm#current 
(Sorry for german language) current is a xpath function...

**Comment by R00dRallec** [comment]
I was able to create a workaround so i dont have to use current(). But I#m still confused, why the same Schematron rule is on time succesfully applied, and in my other project not. 
I removed Xalan from the project, but no change...

**Comment by phax** [comment]
Weird - I tried to make a minimum example and got the error, that "current" is an unknown function.
According to http://stackoverflow.com/questions/3657745/xpath-query-how-to-refer-to-the-current-node-java-saxon this is clearly no XPath and they are suggesting some work around.

What I stumbled upon is, that when updating from Saxon 9.5 to 9.6 it was necessary to prefix all XPath functions with the "fn:" prefix to work.

And btw. your project still used ph-schematron 2.9.0 ;-)

P.S. concerning the German page - no problem, I'm a German native speaker ;-)

**Comment by R00dRallec** [comment]
Yes it's not XPath, my fault.
Updating my Project to 2.9.1 magically resovled the issue and saxon is used to compile the XPath expression. I rewrote my rule, so i don't need the current element any longer. But still weird.

Looking at the stack trace showed, that before my update, com.sun.org.apache.xpath.internal.compiler.XPathParser was used to compile the XPath.

**Comment by phax** [comment]
There was a classloadee issue in 2.9.0 using the system classloader instead of the context classloader. Thats why the update worked :)

Am 13. Februar 2015 15:43:07 MEZ, schrieb R00dRallec <notifications@github.com>:
>Yes it's not XPath, my fault.
>Updating my Project to 2.9.1 magically resovled the issue and saxon is
>used to compile the XPath expression. I rewrote my rule, so i don't
>need the current element any longer. But still weird.
>
>Looking at the stack trace showed, that before my update,
>com.sun.org.apache.xpath.internal.compiler.XPathParser was used to
>compile the XPath.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/phax/ph-schematron/issues/6#issuecomment-74263295

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by R00dRallec** [comment]
Ah nice, but do you have any idea how i could implement the xslt function current() ?
I need this, because the context element has the same attribute like the checked ones from the assertion. Setting a variable like this: <sch:let name"current" value="."/> and accessing like this: test="//Test/@Id = $current/@Id" did not work as supposed.

**Comment by phax** [comment]
Can you do a nested query as suggested in the SO entry like
/import/record[id/text() = ./parent/text()]/data
???

**Comment by R00dRallec** [comment]
No it does not work, it's interpreted as if i would try to check the node in the assertion and not an attribute from the context itself.

**Comment by phax** [comment]
What if you move the attribute from the context to the assert itself.
So instead of context "/element/@attr" you could write:
context "/element" and assertion "(@attr and condition) or (not @attr)"

**Comment by R00dRallec** [comment]
Not possible due to nested conditions.
According to this page: http://www.schematron.com/iso/P8.html the let element is calculated in the current context:
"A declaration of a named variable. If the let element is the child of a rule element, the variable is calculated and scoped to the current rule and context. Otherwise, the variable is calculated with the context of the instance document root.
The required name attribute is the name of the variable. The required value attribute is an expression evaluated in the current context."

So i created this example:
http://pastebin.com/1wraX0P8

http://pastebin.com/ktChYAvi

The assertion fails 3 times. Am i too dumb or is this a bug?
Thanks again for your effort!

**Comment by phax** [comment]
You are right - this is a bug. Currently all lets seem to be evaluated in global scope only. More information to come.

**Comment by R00dRallec** [comment]
I can't get your solution running. I can change the attributes in the xml like i want, the assertion never fails. This cannot be correct :o

**Comment by phax** [comment]
In the current implementation, the "let" handling works like the following: collect all variables in the correct scope. Perform all text replacements in the current XPath. Evaluate the XPath.
That's what I mean with "just a text replacement". The tricky thing is just to get the scope right.

Concerning the example: can you provide an example that is closer to your production issue?

**Comment by phax** [comment]
The following check at least determines files that are not referenced:
<?xml version="1.0" encoding="UTF-8"?>
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron">
  <sch:pattern name="Every file is referenced to one doc">
    <sch:rule context="//file">
      <sch:assert test="count(.[@Id = //reference/@To_File]) = 1">
file <sch:value-of select="@Id" /> is not referenced once but <sch:value-of select="count(.[@Id = //reference/@To_File])" /> times.
      </sch:assert>
    </sch:rule>
  </sch:pattern>
</sch:schema>

**Comment by phax** [comment]
I spend some time with, but couldn't find a suitable solution. When using the XSLT based version instead of the pure version I found a solution:
```xml
    <sch:rule context="//doc">
      <sch:let name="cur" value="." />
      <sch:assert test="count(//reference[@To_File = $cur/generic/reference/@To_File]) = 1">
        file <sch:value-of select="generic/reference/@To_File" /> referenced from document <sch:value-of select="@Id" /> is referenced <sch:value-of select="count(//reference[@To_File = $cur/generic/reference/@To_File])" /> times overall
      </sch:assert>
    </sch:rule>
```

So the let handling is different between Pure and XSLT. XSLT seems to really evaluate the variable in the current context and pass the evaluation result into the test expression.... If this is not an option please file a separate issue.

**Comment by R00dRallec** [comment]
Wow, using the AbstractSchematronResource as you did in your testcase allows me to use the xslt function current(). So there is no longer a need for the variable. 
But can i add my own MapBasedXPathFunctionResolver to an AbstractSchematronResource?

**Comment by phax** [comment]
As far as I know this is only possible with XPath. You may use extensive "let"s :)

**Comment by R00dRallec** [comment]
Thank you very much!
This issue is closed now.
