### ISSUE TITLE
Add option to remove conflicting quickfix elements

### ISSUE THREAD

**Issue by xephon2** [phax/ph-schematron#61]
The Schematron Quickfix elements throw several errors. It would be good, if they would be removed in the normalization step.

```
[schematron] Warning: unrecognized element sqf:fix
```

**Comment by AndrewSales** [comment]
Does passing the parameter `[allow-foreign](https://github.com/Schematron/schematron/blob/master/trunk/schematron/code/iso_svrl_for_xslt2.xsl#L188)` to the XSLT processor alleviate this?

**Comment by phax** [comment]
@AndrewSales Thanks a lot - that does the trick.

Code snippet to achieve this directly:
```
    final SchematronResourceSCH aRes = ...;
    final Map <String, Object> aParams = new HashMap <> ();
    aParams.put ("allow-foreign", "true");
    aRes.setParameters (aParams);
```

**Comment by phax** [comment]
Now it got more easy to use:
```java
   final ISchematronXSLTBasedResource aRes = ...;
    aRes.setAllowForeignElements (true);
 ```
Usable as of v5.0.2
