### ISSUE TITLE
Ant: Add new failure controller attribute

### ISSUE THREAD

**Issue by xephon2** [phax/ph-schematron#66]
I like to break the build for some error levels, not for all. The `failOnError` is boolean, so cannot be used to do this. What I'd like to have is something like this:

```xml
failOnRole="fatal,error,warning"
```

**Comment by phax** [comment]
fyi: currently there is a heuristics contained that takes into consideration:
* for fatal error: `fatal`, `fatalerror`, `fatal_error`, `fatal-error` (since 5.0.2)
* for error: `error`, `err`:
* for warning: `warning`, `warn`
* for information (since 5.0.2): `information`, `info`, `notice`, `note`.

**Comment by phax** [comment]
I did it slightly different. There is a list of `errorRole` elements that define additional `role` and `flag` values that are interpreted as error. E.g.
```xml
      <errorRole role="foo" />
      <errorRole role="bar" />
```
These error roles are handle with precendence, but if not contained, it falls back to the default error levels as stated above.

**Comment by fviolette** [comment]
Do you confirm `<report>`s are properly handled according to the errorRole(s) defined?

With `failOnError` set to true and `<errorRole role="fatal"/>`, my test chokes on the first `<report test="." role="info">...</report>`.

It is properly ignored when turning it into `<assert test="not(.)" role="info">...</assert>`.

**Comment by phax** [comment]
@fviolette I added a second unit test for this issue with "report" elements. And to me it looks fine.
But there is an incosnstency in your test: "errorRole" uses "fatal", the "report" uses "info" - was that accidental?

**Comment by fviolette** [comment]
I meant the a report role="info" returned an error, which I did not expect by setting <errorRole role="fatal"/>. Did I misunderstand anything?

I am going to check your unit test and double check my issues.

**Comment by phax** [comment]
Thanks all. Found it. Sorry - copy paste error for reports only :( Will do 5.0.5 asap

**Comment by fviolette** [comment]
You seriously _rule_!

**Comment by fviolette** [comment]
All good now.

**Comment by phax** [comment]
Excellent - thanks for rechecking!
