### ISSUE TITLE
Schematron analysis for multiple xml files

### ISSUE THREAD

**Issue by navjottiwana** [phax/ph-schematron#69]
I am trying to analyze 20 xml files with a single .sch rules using schematron maven plugin. The build is failing at 3rd xml file. I want schematron to analyze all 20 xml files and then fail the build. Can you please suggest.

**Comment by phax** [comment]
Unfortunately this is not possible atm. I consider this an extension request :)

**Comment by navjottiwana** [comment]
Hi Phax, Thanks for the enhancement :) . Can you please let me know by when v5.0.5 will be rolled out ?
