### ISSUE TITLE
Simpler Invoicing XSL not working

### ISSUE THREAD

**Issue by LeiSun-1101** [phax/ph-schematron#73]
Hi:

I like to use the simpler invoicing 2.0 schematron file to validate some xmls. However, it doesn't work. 
It always complain that the schematron is not valid. The schematron file is https://github.com/SimplerInvoicing/validation/blob/master/schematron/si-ubl-2.0-RC1.sch .

Thanks a lot for the help.

Regards
Lei

**Comment by phax** [comment]
Hi Lei,
what implementation are you using? Most likely you need to use "XSLT" based version and not the pure version.
I already run SimplerInvoicing validation (1.1 and 1.2) using the XSLT approach.
hth, Philip

**Comment by LeiSun-1101** [comment]
Hi Phax:

I am new in this field. I want to know XSLT approach. Does it means that I use the XSL file generated from schematron with your ph-schematron?

Reagrds
Lei

**Comment by phax** [comment]
Hi Lei,
I have a different set of libraries ( https://github.com/phax/ph-bdve ) - that wraps the payload specific validation. I would add SimplerInvoicing 2.0 RC1 to it.
Would that help?
// Philip

**Comment by LeiSun-1101** [comment]
Hi Phx:

That's really helpful. Thanks a lot.

Regards
Lei

**Comment by phax** [comment]
Lets continue there :)
