### ISSUE TITLE
Pass parameters to pure version possible?

### ISSUE THREAD

**Issue by rsamant14** [phax/ph-schematron#74]
Is it possible to send in parameters that can be populated in 
 <let name="somevalue"/> in the sch file when using the pure version (or is that only applicable in the xslt version.

I am seeing considerable performance benefits of using the pure version, and am trying to convert my sch to a pure version.

Appreciate the help.

**Comment by phax** [comment]
There are 2 kinds of parameters, depending on the solution you are using:

* Pure and XSLT version: 1. parameters for Schematron variables
* SCH version: 1. parameters for Schematron variables and 2. parameters for the XSLT script used to create the XSLT script

Hope that resolves the confusion :)
The "how" depends on the way you are using it (Java code, Maven plugin, ANT task)

**Comment by rsamant14** [comment]
Thank you. Appreciate the help.
