### ISSUE TITLE
Duplicate files in ph-schematron-validator

### ISSUE THREAD

**Issue by bahaabeih** [phax/ph-schematron#76]
Just noticed `ph-schematron\ph-schematron-validator\src\test\resources\schemas\iso-schematron-2016.xsd` and `ph-schematron\ph-schematron-validator\src\test\resources\schemas\iso-schematron-2016.rng` both have rng content

**Comment by phax** [comment]
Thanks for pointing that out. That was also wrong for the -2006 version.
