### ISSUE TITLE
Unable to resolve ph-jaxb

### ISSUE THREAD

**Issue by Novaax** [phax/ph-schematron#79]
Hello,
when I try to include ph-schematron in my project, the Gradle Process can't find the ph-jaxb library.

So I looked at MavenCentral to see if there was a working reference to project, but unfortunately the compile path there didn't help.

**Comment by phax** [comment]
Hi, this is a known problem in Gradle, that it does not support Java version based profile activation.
Please see https://github.com/phax/ph-jaxb-pom#gradle-usage for details.

**Comment by Novaax** [comment]
Hello,
Thank you very much for the link. I also had to exclude the pom file from the build.

`compile group: 'com.helger', name: 'ph-schematron', version: '5.2.0',
            {
                exclude group: 'com.helper', module: 'ph-jaxb-pom'
            }
`

**Comment by phax** [comment]
Ah okay - thanks. I will update the documentation accordingly :)
