### ISSUE TITLE
Pass in parameter to Schematron file

### ISSUE THREAD

**Issue by btiernay** [phax/ph-schematron#8]
It would be very useful to be able to pass in data to a schematron file. For example, `document()` file paths, etc. Is this currently supported?

**Comment by phax** [comment]
Are you using the Pure or the XSLT based version?
When using the XSLT based variant, you can use any XSLT function...

**Comment by btiernay** [comment]
Im using xslt. However,  I would like the the ability to use something like `<xsl:param>` to externalize runtime parameters.

**Comment by phax** [comment]
This is currently not possible, but I will add this to the next version!

**Comment by btiernay** [comment]
That would be great! For now I can simply write my arguments to a `params.xml` file and read them in with `document('params.xml')`.

**Comment by phax** [comment]
I think your way is suitable.

I was playing around with the global Transformer parameters but they are only accepted, when a respective top-level "param" is present in the created XSLT.
A global XSLT param can currently only be created, when a respective global "sch:let" with name AND value is provided. When removing the "value" attribute, and XSLT variable was created instead, so I changed this in the XSLTs!

If you find time playing around with the trunk, please have a look at https://github.com/phax/ph-schematron/blob/master/src/test/java/com/helger/schematron/supplemantery/TestIssue8.java and the referenced test files.

hth

**Comment by BatScream** [comment]
The link seems to be broken, this is the updated [link](https://github.com/phax/ph-schematron/blob/master/ph-schematron/src/test/java/com/helger/schematron/supplementary/Issue8Test.java).

**Comment by phax** [comment]
Thank you - text fixed :)

**Comment by peterbomberg** [comment]
Any updates on supporting param's instead of only locally defined variables?

**Comment by phax** [comment]
Well, I changed it locally in my XSLT, but got no response on the issue posted at the Schematron project.
For an example on how to pass in parameters from the outside, refer to the test at https://github.com/phax/ph-schematron/blob/master/ph-schematron/src/test/java/com/helger/schematron/supplementary/Issue8Test.java
