### ISSUE TITLE
Register PSXPathQueryBinding for query binding "xpath2"

### ISSUE THREAD

**Issue by dmj** [phax/ph-schematron#80]
ISO Schematron 2016 added Annex I with a non-normative definition of an XPath 2.0 query binding. Currently ph-schematron accepts only ```xslt``` and ```xslt2``` as query binding tokens and reports a schema as invalid if it uses ```xpath2```.

**Comment by phax** [comment]
Thx. Will do immediately after my vacation :)

**Comment by phax** [comment]
Fixed in v5.2.1
