### ISSUE TITLE
Cache Schematron/XSLT Files before validation

### ISSUE THREAD

**Issue by Novaax** [phax/ph-schematron#81]
Hello,
is it possible to cache the schematron/XSLT before validation?  (without running applySchematronValidation or applySchematronValidationToSVRL)

**Comment by phax** [comment]
They are indeed cached internally. But for every restart of the application the cache needs to be rebuild. The best thing from a performance perspective is to convert the SCH to XSLT once (e.g. using the Maven plugin) and than use the Xslt...

**Comment by Novaax** [comment]
Thank for your help 👍 

I am now facing a problem when validating an XML file with an XSLT reformatted from a .SCH file. When I trigger the validation using the following function, the validation takes up to 20 seconds. If I run another one after the first validation it will run within 6 seconds.

`ISchematronResource XReslt1 = SchematronResourceXSLT.fromFile(Paths.get("/test/zugferd2p0_extended.xslt").toFile());
XReslt1.applySchematronValidationToSVRL(new StreamSource(new File("testFile.xml"));`

The following questions have yet to be answered:
- When is the internal cache set up, with which function?
- Do you have a hint for how I can optimize the processing?

I have also attached the test files I tested with.


[XSLTandSCH.zip](https://github.com/phax/ph-schematron/files/3452691/XSLTandSCH.zip)

**Comment by phax** [comment]
This happens deep inside the code and cannot be easily triggered explicitly.
I will respond in more detail after my vacation

**Comment by phax** [comment]
The main caching (conversion to a `Templates` object) happens in the constructor of class `SchematronProviderXSLTPrebuild` (assuming you start from a converted XSLT).
This instance itself is created in `SchematronResourceXSLT` if caching is enabled (which is the default).
A trick to "enforce caching" (aka precompilation) is to call `isValidSchematron ()` on the `ISchematronResource` object. This will do the trick.
hth

**Comment by phax** [comment]
I'm closing this - if you need more details -  just ask
