### ISSUE TITLE
Language tag of a diagnostic is not preserved in SVRL output

### ISSUE THREAD

**Issue by dmj** [phax/ph-schematron#82]
Using the following Schematron:

```
<sch:schema>
  <sch:pattern>
    <sch:rule context="/">
      <sch:report test="true()" diagnostics="d1"/>
    </sch:rule>
  </sch:pattern>
  <sch:diagnostics>
    <sch:diagnostic id="d1" xml:lang="de">Foobar</sch:diagnostic>
  </sch:diagnostics>
</sch:schema>
```

I expect the SVRL to contain a svrl:successful-report with a svrl:diagnostic-reference that contains a svrl:text element with the @‍xml:lang set to 'de'.

But with ph-schematron 5.2.0 I get:

```
<schematron-output xmlns="http://purl.oclc.org/dsdl/svrl">
  <active-pattern/>
  <fired-rule context="/"/>
  <successful-report location="#document" test="true()">
    <diagnostic-reference diagnostic="d1">
      <text>Foobar</text>
    </diagnostic-reference>
    <text/>
  </successful-report>
</schematron-output>
```
This was discovered with running ph-schematron 5.2.0 against a in-progress schematron testsuite. The complete test results are shown [here](https://schxslt.dmaus.name/testsuite).

**Comment by phax** [comment]
Hi @dmj 
can you please elaborate (and this holds true for all issues you reported), how you performed the validation? Using the XSLT or using "Pure" mode? Since pure mode only handles XPath and not XSLT, all the "document-uri" functions etc. are not working.
Thanks,

**Comment by dmj** [comment]
Sorry, forgot that. I am using the "Pure" mode and took care to only use XPath-functions in the tests. All tests for the xpath2 query binding are found here:

https://github.com/schxslt/schxslt-testsuite/tree/master/testsuite/tests/xpath2

For every test there is a testcase description (*.xml) and a schematron (*.sch). The testcase description references the primary instance document and the expected result. 

[This one](https://github.com/schxslt/schxslt-testsuite/blob/master/testsuite/tests/xpath2/svrl-diagnostic-language.xml) (diagnostics in SVRL)  is marked as optional because SVRL is no normative part of the Schematron spec.

**Comment by phax** [comment]
With my change of #85 the `xml:lang` attribute is now also maintained in the diagnostic-reference. Will be part of the 6.0.2 release.
