### ISSUE TITLE
PSSchema made Schematron File   with  no prefix 

### ISSUE THREAD

**Issue by SnowMakerDemo** [phax/ph-schematron#87]
PSSchema made 

 
![image](https://user-images.githubusercontent.com/28621460/65428754-85c78300-de47-11e9-8cc0-259dfb86b612.png)

i want 

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:xsl="http://www.w3.org/1999/XSL/Transform" queryBinding="xslt2">
<sch:ns prefix="xs" uri="http://www.w3.org/2001/XMLSchema"/>

no  prefix "sch:"; 
what shoud i do  ,i can not  find the  method for this.   thank you  .   :)

**Comment by phax** [comment]
Hello,
this works, but is a little bit tedious ;-)
I created the following snippet that works with the latest version:
```java
    final PSSchema aSchema = /* your job */;

    // Create the XML namespace context
    final MapBasedNamespaceContext aNSCtx = new MapBasedNamespaceContext ();
    aNSCtx.addMapping ("sch", CSchematron.NAMESPACE_SCHEMATRON);
    aNSCtx.addMapping ("xsl", "http://www.w3.org/1999/XSL/Transform");
    // Add all mappings from the PSSchema as well
    for (final PSNS aItem : aSchema.getAllNSs ())
      aNSCtx.addMapping (aItem.getPrefix (), aItem.getUri ());

    // Create the PSWriter settings
    final PSWriterSettings aPSWS = new PSWriterSettings ();
    aPSWS.setXMLWriterSettings (new XMLWriterSettings ().setNamespaceContext (aNSCtx)
                                                        .setPutNamespaceContextPrefixesInRoot (true));

    // Write the Schematron
    new PSWriter (aPSWS).writeToFile (aSchema, new File ("target/test-with-nsprefix.xml"));
```

**Comment by SnowMakerDemo** [comment]
WOW，let me try  ,  :）, thank you  ， so surprise that  you response so timely  . thank you.

**Comment by SnowMakerDemo** [comment]
it worked。 prefixes are all the same  ‘sch’ , but  i want   <xsl:include href="./functions.xsl" />   ,the prefix is 'xsl',what should  i do,  :)   thank  you 。

**Comment by phax** [comment]
Well I guess, this is because your source Schematron contains the "Schematron-include" and not the "XSLT-include".
Can you paste the relevant parts of the Schematron here? Or are you creating the Schema programmatically?

**Comment by SnowMakerDemo** [comment]
yes,I modified my file，it worked。 thank you   :)    i want to cache my shcematron   ,how to  preprocess   the schematron which has 'xslt' in it.  
code 👍 
 IReadableResource aRes = new FileSystemResource (file);
        final CollectingTransformErrorListener aCEH = new CollectingTransformErrorListener ();
        final ISchematronXSLTBasedProvider aPreprocessor = SchematronResourceSCHCache.createSchematronXSLTProvider (aRes,
                                    new SCHTransformerCustomizer().setErrorListener (aCEH)
                        .setLanguageCode ("en")); 

these codes can do that?

**Comment by SnowMakerDemo** [comment]
hello  , 
 java code : 
        File child = new File("D:\\test\\schematron-test.sch");
        IReadableResource aRes = new FileSystemResource (child);
        final CollectingTransformErrorListener aCEH = new CollectingTransformErrorListener ();
        final ISchematronXSLTBasedProvider aPreprocessor = SchematronResourceSCHCache.getSchematronXSLTProvider (aRes,
                new SCHTransformerCustomizer().setErrorListener (aCEH)
                        .setLanguageCode ("de"));

       
       /* final SchematronResourceSCH aSCH = SchematronResourceSCH.fromFile(child);
        aSCH.setAllowForeignElements(true);
        SchematronOutputType res = aSCH.applySchematronValidationToSVRL(new FileSystemResource(new File("D:\\test.xsd")));
        System.out.println(res);*/

sch code:
        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:xsl="http://www.w3.org/1999/XSL/Transform" queryBinding="xslt2">
    <sch:title>Rules for extension XML Schema documents</sch:title>

    <xsl:include href="ndr-functions.xsl"/>

    <sch:ns prefix="xs" uri="http://www.w3.org/2001/XMLSchema"/>
    <sch:ns prefix="xsl" uri="http://www.w3.org/1999/XSL/Transform"/>
    <sch:ns prefix="nf" uri="http://reference.niem.gov/niem/specification/naming-and-design-rules/4.0/#NDRFunctions"/>
    <sch:ns prefix="ct" uri="http://release.niem.gov/niem/conformanceTargets/3.0/"/>
    <sch:ns prefix="xsi" uri="http://www.w3.org/2001/XMLSchema-instance"/>

    <sch:pattern id="Rule7-4"><sch:title> Document element is xs:schema</sch:title>
        <sch:rule context="*[. is nf:get-document-element(.)]">
            <sch:assert test="self::xs:schema">Rule 7-4: The [document element] of the [XML document] MUST have the name xs:schema.</sch:assert>
        </sch:rule>
    </sch:pattern>
</sch:schema>

xsl code: 
<?xml version="1.0" encoding="UTF-8"?>
<stylesheet
  version="2.0"
  xmlns:catalog="urn:oasis:names:tc:entity:xmlns:xml:catalog"
  xmlns:impl="http://example.org/impl"
  xmlns:nf="http://reference.niem.gov/niem/specification/naming-and-design-rules/4.0/#NDRFunctions"
  xmlns:saxon="http://saxon.sf.net/"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://www.w3.org/1999/XSL/Transform">
  
  <param name="xml-catalog" as="document-node()?"/>
  
  <function name="nf:get-document-element" as="element()">
    <param name="context" as="element()"/>
    <sequence select="root($context)/*"/>
  </function>

</stylesheet>


error messages:
 Error XTDE1162 while evaluating xsl:message at line 1923 of jar:file:/D:/work/apache-maven-3.5.3/repository/com/helger/ph-schematron/5.2.0/ph-schematron-5.2.0.jar!/schematron/20100710-xslt2/iso_schematron_skeleton_for_saxon.xsl: The second argument to document() is a node with no base URI
2019-09-25 09:53:22.764 ERROR 12488 --- [           main] c.h.xml.transform.XMLTransformerFactory  : Failed to parse javax.xml.transform.dom.DOMSource@123307c4

javax.xml.transform.TransformerConfigurationException: net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
	at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:152) ~[Saxon-HE-9.9.1-3.jar:na]
	at com.helger.xml.transform.XMLTransformerFactory.newTemplates(XMLTransformerFactory.java:300) ~[ph-xml-9.3.4.jar:9.3.4]
	at com.helger.schematron.xslt.SchematronProviderXSLTFromSCH.<init>(SchematronProviderXSLTFromSCH.java:195) [ph-schematron-5.2.0.jar:5.2.0]
	at com.helger.schematron.xslt.SchematronResourceSCHCache.createSchematronXSLTProvider(SchematronResourceSCHCache.java:69) [ph-schematron-5.2.0.jar:5.2.0]
	at com.helger.schematron.xslt.SchematronResourceSCHCache.getSchematronXSLTProvider(SchematronResourceSCHCache.java:145) [ph-schematron-5.2.0.jar:5.2.0]
	at com.demo.schematron.runner.SimosApplicationRunner.run(SimosApplicationRunner.java:37) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:772) [spring-boot-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:762) [spring-boot-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319) [spring-boot-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) [spring-boot-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at com.demo.schematron.SchematronApplication.main(SchematronApplication.java:10) [classes/:na]
Caused by: net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:788) ~[Saxon-HE-9.9.1-3.jar:na]
	at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:149) ~[Saxon-HE-9.9.1-3.jar:na]
	... 11 common frames omitted
Caused by: net.sf.saxon.trans.XPathException: Errors were reported during stylesheet compilation
	at net.sf.saxon.style.StylesheetModule.loadStylesheet(StylesheetModule.java:261) ~[Saxon-HE-9.9.1-3.jar:na]
	at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:107) ~[Saxon-HE-9.9.1-3.jar:na]
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:785) ~[Saxon-HE-9.9.1-3.jar:na]
	... 12 common frames omitted

2019-09-25 09:53:22.764  WARN 12488 --- [           main] c.h.s.xslt.SchematronResourceSCHCache    : The Schematron resource 'D:\work\CIEM\sch\test\schematron-test.sch' is invalid! 

i dont know  why.  :(   , help! help!  help!   thank you.

**Comment by SnowMakerDemo** [comment]
![image](https://user-images.githubusercontent.com/28621460/65572442-afdd8a00-df9a-11e9-9449-73fd3e025d61.png)
("allow-foreign","true" )    without cache handling ,    i want to  cache the preprocess schamatron ,what shoud i do,  thank you.
xsl : 
<?xml version="1.0" encoding="UTF-8"?>
<stylesheet
  version="2.0"
  xmlns:catalog="urn:oasis:names:tc:entity:xmlns:xml:catalog"
  xmlns:impl="http://example.org/impl"
  xmlns:nf="http://reference.niem.gov/niem/specification/naming-and-design-rules/4.0/#NDRFunctions"
  xmlns:saxon="http://saxon.sf.net/"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://www.w3.org/1999/XSL/Transform">
  
  <param name="xml-catalog" as="document-node()?"/>
  
  <function name="nf:get-document-element" as="element()">
    <param name="context" as="element()"/>
    <sequence select="root($context)/*"/>
  </function>

</stylesheet>

sch:
<?xml version="1.0" encoding="UTF-8"?>
<stylesheet
  version="2.0"
  xmlns:catalog="urn:oasis:names:tc:entity:xmlns:xml:catalog"
  xmlns:impl="http://example.org/impl"
  xmlns:nf="http://reference.niem.gov/niem/specification/naming-and-design-rules/4.0/#NDRFunctions"
  xmlns:saxon="http://saxon.sf.net/"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://www.w3.org/1999/XSL/Transform">
  
  <param name="xml-catalog" as="document-node()?"/>
  
  <function name="nf:get-document-element" as="element()">
    <param name="context" as="element()"/>
    <sequence select="root($context)/*"/>
  </function>

</stylesheet>

**Comment by SnowMakerDemo** [comment]
Hi, I've been thinking about it for a few days, but I can't find a good way to cache files with custom parameters. Reading files takes a long time. Do you have any good Suggestions? Thank you!

**Comment by phax** [comment]
I added the method `SCHTransformerCustomizer.setForceCacheResult(boolean)`

**Comment by SnowMakerDemo** [comment]
thank you very much  .:):):):):):):):):):):):):):):):):):):):):):):):):):):):):):):):)

**Comment by phax** [comment]
Please close the issue, if that works for you.
