### ISSUE TITLE
I suggest that key  of the cache should be changed

### ISSUE THREAD

**Issue by SnowMakerDemo** [phax/ph-schematron#89]
![image](https://user-images.githubusercontent.com/28621460/66379759-ac112500-e9e8-11e9-8696-4fc79b745708.png)
I suggest that the cache key include file md5 encrypted value, then the file changes the cache will also change.   or  The cache can be cleared .  :)

**Comment by phax** [comment]
With issue #109 this can also be resolved I assume. If not, please re-open.
