### ISSUE TITLE
Add support for registering custom XPath functions

### ISSUE THREAD

**Issue by btiernay** [phax/ph-schematron#9]
I'm not sure if this is possible. I did notice some classes in the project that seemed to indicate that this was supported. If so, is there an example I could follow?

**Comment by phax** [comment]
This is not possible as far as I know. As I'm not an XSTL expert - if you have any input for me, I'd very much appreciate it.
Internally I'm working on the regular "Transformer" object, which does not offer to provide custom XPath functions. Only the "pure" implementation, which directly works on the XPath can explicitly handle custom XPath variables and functions.

**Comment by btiernay** [comment]
It looks like this should be possible if you are using Saxon:

http://saxon.sourceforge.net/saxon6.5/extensibility.html#Writing-extension-functions

Although, I too have to admit very little experience here. However, adding support for this would be very useful in situations where one needs to interface with external systems for validation checks.

**Comment by phax** [comment]
Please try the method suggested in http://cafeconleche.org/books/xmljava/chapters/ch17s03.html - seems like no changes are necessary. E.g.
```
  <xsl:template match="int"
                xmlns:fib="java:com.macfaq.math.FibonacciNumber">
    <int>
      <xsl:value-of select="fib:calculate(number(.))"/>
    </int>
  </xsl:template>```
