### ISSUE TITLE
Some links are dead

### ISSUE THREAD

**Issue by nkutsche** [phax/ph-schematron#92]
Hi,

found some dead links:

* In the [README.md#declare-the-task](https://github.com/phax/ph-schematron#declare-the-task) section the link to the Maven Central needs the https protocol.
* The HomePage link in Maven Central e.g. [here](https://mvnrepository.com/artifact/com.helger/ph-schematron/5.4.0) is dead.

**Comment by phax** [comment]
Thanks for pointing that out and providing the fix
