### ISSUE TITLE
Invalid Schematron when use the expression &lt; in the schematron

### ISSUE THREAD

**Issue by manuelhcosta** [phax/ph-schematron#99]
Hello,

I' trying to validate an XML with schematron using your API. 
When I use the  &lt; in the schematron file it give me the error: "java.lang.IllegalArgumentException: Invalid Schematron!".

Is it possible to use &lt; in your schematron API to use condition like "A < 1" ?

Below you can see the line with the expression "&lt;" that provoke the invalid schematron:

<report test="starts-with(normalize-space(.),'#CALCULATIONRATE#') and $cnt20_2 &lt; 1" id="DT-CIUS-PT-020_2.3" flag="fatal">[DT-CIUS-PT-020_2.3]-The BT-22 when prefixed with '#SOURCECURRENCYCODE#', is mandatory if an element with the prefix '#CALCULATIONRATE#' has been or will be referenced.</report>

Thanks in advance.

King Regards,

Manuel

**Comment by manuelhcosta** [comment]
Here you can see the the expression:

[UBL-TR_Common_Schematron.zip](https://github.com/phax/ph-schematron/files/4313735/UBL-TR_Common_Schematron.zip)

**Comment by phax** [comment]
Hi. I am on my phone only so I am guessing : is it possible that either
* the variable $cnt... Is not resolved
* or you need brackets around the (A < 1) part?

**Comment by phax** [comment]
In general the usage of "<" is not a problem at all. It is a regular XPath operator

**Comment by manuelhcosta** [comment]
The problem is that $cnt20_2 is not resolved. 

I try <let name="cnt20_2" value="2"/> and it works.

Thanks.

Regards,

**Comment by manuelhcosta** [comment]
Hello again,

The problem is that the cnt20_2 is not resolved using the expression "count(filter((ancestor::ubl:Invoice/cbc:Note | ancestor::cn:CreditNote/cbc:Note),function($a){matches($a,'^(#(SOURCECURRENCYCODE)#(.{1,})#)$')}))"

I assuming that the expression is correct because is used for UBL 2.1 Invoice an it works in other validations, can you see the reason for not resolve the $cnt20_2?

In attach I send you the UBL 2.1 Invoice and the respective schematron.

Thanks in advance.

Regards,

Manuel Costa

[UBL_Example.zip](https://github.com/phax/ph-schematron/files/4314367/UBL_Example.zip)

**Comment by phax** [comment]
I haven't tested it, but try putting the "let" before the "assert".
What engine are you using for evaluation (XSLT or Pure)?

**Comment by manuelhcosta** [comment]
Hello Philip,

I put the "let" before and the result is the same error.
I use XSLT engine for evolution.

Regards,

Manuel

**Comment by manuelhcosta** [comment]
The Code that I use is:
	  public static boolean validateXMLViaPureSchematron (final File aSchematronFile, final File aXMLFile) throws Exception
	  {
		final IReadableResource anXMLSource = new FileSystemResource (aXMLFile.getAbsoluteFile ());
	    final ISchematronResource aResPure = SchematronResourcePure.fromFile (aSchematronFile);


	    //System.out.println ("Valid Åžematron mu? " + aResPure.isValidSchematron ());
	    if (!aResPure.isValidSchematron())
	     throw new IllegalArgumentException("Invalid Schematron!");
	    
	    final SchematronOutputType aSVRL = aResPure.applySchematronValidationToSVRL (anXMLSource);
	    System.out.println (new SVRLMarshaller ().getAsString (aSVRL));

	    return aResPure.getSchematronValidity (new StreamSource (aXMLFile)).isValid ();
	  }

**Comment by phax** [comment]
Than you are not using the XSLT version. Try replacing `SchematronResourcePure` with `SchematronResourceSCH`.

**Comment by manuelhcosta** [comment]
I change it to: 	    final ISchematronResource aResPure = SchematronResourceSCH.fromFile (aSchematronFile);

but now the program is hanging.

**Comment by phax** [comment]
Give it some time please. This precompilation from SCH to XSLT can take several (!) minutes. I just want to know if it works or not.

**Comment by manuelhcosta** [comment]
It still running.
Is it possible that this API can validate the UBL Invoice 2.1? 
I send you in attach the shematron standard  to validate the UBL Invoice 2.1 (urn_feap.gov.pt_CIUS-PT_1.0.6.sch) and an example of UBL Invoice 2.1 (all_DN_CIUS-PT.xml)

**Comment by phax** [comment]
Yes please send it by email. But I cannot work on this tomorrow. You need to wait until next week.

**Comment by manuelhcosta** [comment]
Sorry I forgot the attach.

Ok I wait until next week.

Thanks.

[schematron.zip](https://github.com/phax/ph-schematron/files/4325495/schematron.zip)

**Comment by manuelhcosta** [comment]
Hello Philip,

I send you in attach the shematron standard to validate the UBL Invoice 2.1
(urn_feap.gov.pt_CIUS-PT_1.0.6.sch) and an example of UBL Invoice 2.1
(all_DN_CIUS-PT.xml) .

Thanks in advance.

Regards,

Manuel Costa

**Comment by phax** [comment]
Hi Manuel,
okay, after 7 minutes I received the following output when using the `SchematronResourceSCH`:
```
[fatal_error] Transformation fatal error (net.sf.saxon.trans.XPathException: Inline functions require support for higher-order-functions, which needs Saxon-PE or higher)
[fatal_error] Transformation fatal error (net.sf.saxon.trans.XPathException: Inline functions require support for higher-order-functions, which needs Saxon-PE or higher)
[fatal_error] Transformation fatal error (net.sf.saxon.trans.XPathException: Inline functions require support for higher-order-functions, which needs Saxon-PE or higher)
[fatal_error] @ (?:103) Transformation fatal error (net.sf.saxon.trans.XPathException: Unexpected token "}" at start of expression)
[fatal_error] Transformation fatal error (net.sf.saxon.trans.XPathException: Inline functions require support for higher-order-functions, which needs Saxon-PE or higher)
[fatal_error] @ (?:97) Transformation fatal error (net.sf.saxon.trans.XPathException: Unexpected token "}" at start of expression)
[fatal_error] Transformation fatal error (net.sf.saxon.trans.XPathException: Inline functions require support for higher-order-functions, which needs Saxon-PE or higher)
[fatal_error] Transformation fatal error (net.sf.saxon.trans.XPathException: Inline functions require support for higher-order-functions, which needs Saxon-PE or higher)
[fatal_error] @ (?:117) Transformation fatal error (net.sf.saxon.trans.XPathException: Unexpected token "}" at start of expression)
[fatal_error] Transformation fatal error (net.sf.saxon.trans.XPathException: Inline functions require support for higher-order-functions, which needs Saxon-PE or higher)
[fatal_error] @ (?:121) Transformation fatal error (net.sf.saxon.trans.XPathException: Unexpected token "}" at start of expression)
[fatal_error] Transformation fatal error (net.sf.saxon.trans.XPathException: Inline functions require support for higher-order-functions, which needs Saxon-PE or higher)
[fatal_error] @ (?:127) Transformation fatal error (net.sf.saxon.trans.XPathException: Unexpected token "}" at start of expression)
[fatal_error] @ (?:158) Transformation fatal error (net.sf.saxon.trans.XPathException: Unexpected token "}" at start of expression)
[fatal_error] @ (?:148) Transformation fatal error (net.sf.saxon.trans.XPathException: Unexpected token "}" at start of expression)
[fatal_error] @ (?:144) Transformation fatal error (net.sf.saxon.trans.XPathException: Unexpected token "}" at start of expression)
[fatal_error] @ (?:112) Transformation fatal error (net.sf.saxon.trans.XPathException: Unexpected token "}" at start of expression)
[fatal_error] @ (?:118) Transformation fatal error (net.sf.saxon.trans.XPathException: Unexpected token "}" at start of expression)
[fatal_error] @ (?:112) Transformation fatal error (net.sf.saxon.trans.XPathException: Unexpected token "}" at start of expression)
[fatal_error] @ (?:122) Transformation fatal error (net.sf.saxon.trans.XPathException: Unexpected token "}" at start of expression)
[fatal_error] Transformation fatal error (net.sf.saxon.trans.XPathException: Inline functions require support for higher-order-functions, which needs Saxon-PE or higher)
[fatal_error] Transformation fatal error (net.sf.saxon.trans.XPathException: Inline functions require support for higher-order-functions, which needs Saxon-PE or higher)
[fatal_error] Transformation fatal error (net.sf.saxon.trans.XPathException: Inline functions require support for higher-order-functions, which needs Saxon-PE or higher)
```
so basically you need the commerical version of Saxon.

The pure version is a bit more specific on the details:
```
C:\dev\git\ph-schematron\ph-schematron\src\test\resources\issues\github99\urn_feap.gov.pt_CIUS-PT_1.0.6.sch - PSAssertReport - ID BR-CIUS-PT-17 - Failed to compile XPath expression in <assert>: 'count(filter(ancestor::cac:InvoiceLine/cac:Item[cac:ClassifiedTaxCategory/cbc:ID = 'E']/cac:AdditionalItemProperty/cbc:Name | ancestor::cac:CreditNoteLine/cac:Item[cac:ClassifiedTaxCategory/cbc:ID = 'E']/cac:AdditionalItemProperty/cbc:Name,function($a){matches($a,'^(#(TAXEXEMPTIONREASONCODE@CLASSIFIEDTAXCATEGORY)#)$')})) > 0 or count(filter(ancestor::cac:InvoiceLine/cac:Item[cac:ClassifiedTaxCategory/cbc:ID = 'E']/cac:AdditionalItemProperty/cbc:Name | ancestor::cac:CreditNoteLine/cac:Item[cac:ClassifiedTaxCategory/cbc:ID = 'E']/cac:AdditionalItemProperty/cbc:Name,function($a){matches($a,'^(#(TAXEXEMPTIONREASON@CLASSIFIEDTAXCATEGORY)#)$')})) > 0' with the following variables: {$cnt17.1=count(filter(ancestor::cac:InvoiceLine/cac:Item[cac:ClassifiedTaxCategory/cbc:ID = 'E']/cac:AdditionalItemProperty/cbc:Name | ancestor::cac:CreditNoteLine/cac:Item[cac:ClassifiedTaxCategory/cbc:ID = 'E']/cac:AdditionalItemProperty/cbc:Name,function($a){matches($a,'^(#(TAXEXEMPTIONREASONCODE@CLASSIFIEDTAXCATEGORY)#)$')})), $cnt17.2=count(filter(ancestor::cac:InvoiceLine/cac:Item[cac:ClassifiedTaxCategory/cbc:ID = 'E']/cac:AdditionalItemProperty/cbc:Name | ancestor::cac:CreditNoteLine/cac:Item[cac:ClassifiedTaxCategory/cbc:ID = 'E']/cac:AdditionalItemProperty/cbc:Name,function($a){matches($a,'^(#(TAXEXEMPTIONREASON@CLASSIFIEDTAXCATEGORY)#)$')}))}
; Line#: -1; Column#: 240
net.sf.saxon.trans.XPathException: Inline functions require support for higher-order-functions, which needs Saxon-PE or higher
```

as I don't have a commercial version of Saxon I am stuck here....

**Comment by manuelhcosta** [comment]
Hello Philip,

I have to change the schematron to work with the pure engine API.

Thanks for your help.

Regards,

Manuel Costa

**Comment by phax** [comment]
Okay. Please remember to use XPath 2 only.
I am closing this issue for now.

**Comment by manuelhcosta** [comment]
Hello Philip,

With Java 1.8 and and ph-schematron-5.5.0.jar I can validate the UBL
Invoice XML, but the framework where I have to validate this XML use Java
1.7.
When I try to validate with Java 1.7, I receive the
following error: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad
major version; class=com/helger/schematron/ISchematronResource, offset=6.

Is it possible to use  ph-schematron-5.5.0.jar in Java 1.7 ?

Thanks in advance.

Regards,

Manuel Costa

**Comment by phax** [comment]
Responded in #100
